firecracker-microvm/firecracker-containerd

- README.md
Links to contact information in the README were not filled in. This change fixes that. Confirmed manually in the rendered markdown.
> Fix contact links

- snapshotter/README.md
Fixes #19 
Removes a dead link to a non-existant TODO file.
> Remove dead TODO link

- go.mod
- go.sum
- runtime/service.go
This PR updates Firecracker SDK to latest revision (which includes HTTP debug)
> Update Firecracker SDK dependency

- runtime/service.go
This PR adds vsock dial retries.
> Retry vsock dials

- Makefile
- agent/Makefile
- runtime/Makefile
- snapshotter/Makefile
Add dependencies for the non-PHONY targets
Reduce some redundancy
Restructure a little bit for readability
> Makefile improvements

- snapshotter/Makefile
- snapshotter/README.md
- snapshotter/cmd/naive/main.go
- snapshotter/cmd/snapshotter/.gitignore
- snapshotter/naive/naive.go
- snapshotter/naive/naive_test.go
- snapshotter/run.go
This refactors snapshotter to support more than one implementation and renames current implementation to naive.
> Refactor snapshotter entry point

- .golangci.yml
- .travis.yml
- Makefile
- agent/service.go
- runtime/service.go
- snapshotter/naive/naive.go
- snapshotter/naive/naive_test.go
- snapshotter/run.go
Add travis and linter configuration.
Travis will build all plugins and run bunch of linters.
~Note 1: Don't merge this please, want to make sure it works as expected with Travis.~
Note 2: There is no tests/coverage stuff, out of scope of this PR.
> Add Travis and linter files

- agent/main.go
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
Address Issue #35
Ensure that id is set, and note that it is a required argument.  
> verify that id is set

- runtime/service.go
- runtime/service_test.go
*Issue #, if available:*  #40
Detect available vsock CID using `VHOST_VSOCK_SET_GUEST_CID` ioctl
> Detect available vsock context ID dynamically

- README.md
- snapshotter/cmd/devmapper/.gitignore
- snapshotter/cmd/naive/.gitignore
* Updated readme
* Added .gitignore for binaries
> Minor snapshotter updates

- snapshotter/pkg/losetup/losetup.go
- snapshotter/pkg/losetup/losetup_test.go
> Add tests for losetup package

- snapshotter/devmapper/config.go
- snapshotter/devmapper/config_test.go
- snapshotter/pkg/losetup/losetup_test.go
- Adds tests for config
- Addresses some previous issues
> Add config tests

- README.md
- docs/snapshotter.md
More information about snapshotters
> docs: update snapshotter docs with devmapper info

- snapshotter/devmapper/devmapper.go
This PR replaces `complete` with `withTransaction` func so we don't have to return `complete(ctx, trans, err)` on every error.
Also there is no way transaction can be forgotten to Commit/Rollback.
`withTransaction` also reports transaction errors in addition to snapshotter errors.
> Rework transaction handling

- README.md
- docs/getting-started.md
- docs/quickstart.md
~Still a work-in-progress, but some guides to getting started with firecracker-containerd.~
This is now ready for review.
> docs: Getting Started and Quickstart guides

- go.mod
- go.sum
- snapshotter/cmd/devmapper/main.go
- snapshotter/cmd/naive/main.go
- snapshotter/run.go
A bit better handling of snapshotter flags in `Run` (so you can call `Parse` from `main` and check flag values outside callback).
> Better flag parsing in snapshotters

- go.mod
- go.sum
- runtime/service.go
Using higher level abstraction, drives builder, to simplify some code.
> runtime: Updating to use drives builder from SDK

- docs/getting-started.md
Signed-off-by: Mehrdad Arshad Rad <arshad.rad@gmail.com>
Typo issue
> doc typo issue fixed (naive_snapshotter)

- snapshotter/cmd/devmapper/README.md
Signed-off-by: Mehrdad Arshad Rad <arshad.rad@gmail.com>
added dm snapshotter sample config at the readme
> added dm snapshotter sample config

- README.md
> readme: add build status badges

- .buildkite/pipeline.yml
- go.mod
- runtime/Makefile
- runtime/service_test.go
New Makefile target, new buildkite step
> runtime: add make target for tests

- snapshotter/devmapper/pool_device_test.go
Small fix for proper cleanup in `/tmp`
> Proper cleanup in pool device tests

- agent/main.go
Without this, the final container spawned by RunC will be reparented to init, not the shim, and the shim won't receive SIGCHLD upon container death.
#87 is not fixed by this commit, but it's a first step for doing so by ensuring the shim is actually aware of child process deaths.
*Testing done:*
Ran local `go test` and the cool new [CI tests passed](https://buildkite.com/firecracker-microvm/sipsma-firecracker-containerd/builds/1#ebca8ef9-4bc5-4813-9937-076069713561)
Also manually verified from a shell in the VM that previously child process containers were not the children of agent and that now they are (the `agent---sh---pstree` branch):
```
/ # pstree
openrc-init-+-agent---sh---pstree
|-sh---sleep
`-supervise-daemo---agetty
```
By submitting this pull request, …
> Set the agent shim as a subreaper to ensure containers become its children

- agent/Makefile
- examples/Makefile
- runtime/Makefile
- snapshotter/Makefile
- snapshotter/cmd/devmapper/Makefile
- snapshotter/cmd/naive/Makefile
> *: Makefiles should depend on go.mod and go.sum

- runtime/service.go
> runtime: add some debug logs

- firecracker-control/local.go
https://github.com/firecracker-microvm/firecracker-containerd/issues/159
Allow parallel VM creation
> Allow parallel VM creation

- README.md
> readme: Scope build badge to the master branch

- docs/root-filesystem.md
This is a first draft at putting things down that we've talked about in-person.  Still some open questions for the future, but hopefully this gives some context.
> docs: root filesystem design considerations

- README.md
Add security contact details to README
> Add security contact details to README

- internal/vm/task.go
This is a non-ideal fix to an issue where a task exit event could be received
before all stdio has been flushed across vsock connections. Vsocks were closed
when task exit occurs, so this resulted in stdio data being dropped.
The fix here replaces the closing of the vsock connection with setting of a
deadline on the socket. This results gives a 5 second window for any last stdio
data to be flushed before closing the io pipeline down.
The better fix to this issue is:
1. Don't rely on task exit events at all; instead use Wait() from the task API
to monitor task exits.
2. Update Agent and Runtime to flush io before returning Wait() responses.
The better fix described above will be tackled as part of upcoming Exec
support, which will benefit from that change anyways. The fix here should patch …
> Set deadline on vsock ops after exit.

- .buildkite/pipeline.yml
> Removes loop devices before starting job.

- .buildkite/logcheck.sh
> Removes merge commits from DCO validation

- firecracker-control/local.go
https://github.com/firecracker-microvm/firecracker-containerd/issues/195
This PR adds VM ID validation to the plugin.
> Add VM ID validator

- README.md
- docs/getting-started.md
- tools/image-builder/README.md
Update some build docs and provide root filesystem usage details.
> Documentation updates

- agent/service.go
- runtime/service_integ_test.go
Before this, if the initial process of a task had the same ID as an exec in the
task, they would end up using the same FIFO dirs.
Note: This isn't related to any ongoing larger work, I just happened to notice it as I was looking at some code around here for unrelated reasons :-)
> Give task and exec FIFO dirs unique names in VM.

- .travis.yml
- tools/docker/Dockerfile
> Upgrade CI to build with go 1.12.

- firecracker-control/local.go
*Issue #, if available:* #217 
*Description of changes:* Added a method to get the OOM score for containerd process and increment the score by 1 to set shim OOM score
> Set Shim OOM score to +1 of containerd

- docs/getting-started.md
Added the shebang line to the compatibility script in the getting started guide. 
> Add shebang line to compatibility script.

- README.md
> readme: update roadmap section

- runtime/service_integ_test.go
*Issue #267 *
*Description of changes: Removed vda lines assertion*
> Remove vda assertion

- firecracker-control/local.go
- go.mod
- go.sum
- runtime/service.go
NA
Upgrade containerd from v1.3.0-beta.2 to v1.3.0
> Upgrade containerd from v1.3.0-beta.2 to v1.3.0

- runtime/runc_jailer.go
- runtime/runc_jailer_test.go
Before this change, if exposing a device to a jail resulted in newly created
directories under the jail root, the directories were created with 0700 perms
but uid/gid owner set to root. This change results in the same 0700 perms but
chowns the new directories to the jail's uid/gid.
This is important as devices created by the devmapper snapshotter are multiple
levels underneath /dev, which means the jailer code now creates new directories
(as opposed to the naive snapshotter which didn't result in new directories
being created).
Fixes #307, I just happened to run into this exact same bug for different reasons when making an update to the drive mount PR.
By submitting this pull request, I confirm that my contribution is made under the terms of …
> Chown newly created directories in jailer's ExposeDevice method.

- go.mod
- go.sum
Issue #287 
Updated firecracker-go-sdk to last version
> Updated firecracker-go-sdk to last version

- runtime/service_integ_test.go
Add a test that additionally verifies that an entry is available from
the mmds inside the container under a url like
http://169.254.169.254/<key> and has the appropriate value returned.
Signed-off-by: Cody Roseborough <cdr@amazon.com>
*Issue #, if available:* #320 
> Add a test for UpdateVMM checking single entry

- runtime/integ_test.go
- runtime/jailer_integ_test.go
- runtime/service.go
- runtime/service_integ_test.go
Wrote for #307, but @sipsma fixed the issue already :)
It would be nice to have more integration tests around jailer.
> Add integration tests for jailer

- .buildkite/pipeline.yml
- internal/vm/task_test.go
Enable Go's race detector on unit tests.
> Enable Go's race detector on unit tests

- .buildkite/pipeline.yml
- Makefile
- agent/Makefile
- agent/service.go
- examples/taskworkflow.go
- firecracker-control/cmd/containerd/Makefile
- runtime/Makefile
- runtime/service_integ_test.go
> Enable Go's race detector on integration tests

- go.mod
- go.sum
> Upgrade to containerd 1.3.1 and runc 1.0.0-rc9

- internal/vm/ioproxy.go
Issue #367
Changed error log level, to clean up logs.
> Change log level for copying io err

- config/config.go
- config/config.json.example
- config/config_test.go
- runtime/helpers.go
- runtime/helpers_test.go
- runtime/integ_test.go
- runtime/service_test.go
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
Issue #359 
Made vcpuCount configuration same as memSizeMb:
> Made vcpuCount configuration same as memSizeMb

- runtime/jailer_test.go
- runtime/runc_jailer.go
NA
Filesystem images are often big (multiple GBs) but sparse (have
zeros inside). At least mkfs.ext4 makes them as sparse files, but
io.Copy ignores the fact and copy all zeros as is, which is slow and
ineffecent.
This change adds sparse file support which makes runc_jailer's initial
file copy faster.
> Copy sparse files as spase files

- .buildkite/al2_cleanup.sh
- .buildkite/al2_pipeline.yml
- .buildkite/al2_test.sh
- .buildkite/al2env.sh
- .buildkite/hooks/pre-exit
- .buildkite/setup_al2.sh
- Makefile
- config/config.go
- runtime/integ_test.go
- runtime/jailer.go
- runtime/runc_jailer.go
- runtime/runc_jailer_test.go
- runtime/service_integ_test.go
- tools/image-builder/Makefile
This change adds an al2_pipeline.yml file that will be used to run tests
on AL2. Also, we have a series of scripts, one for setting up the AL2
environment to test against and the actual test runner itself.
> Adding AL2 pipeline.yml

- runtime/service_integ_test.go
NA
Seems like we accidentally disabled the test on the Docker-based build.
> Run TestMultipleVMs_Isolated on Docker-based build again

- .github/workflows/build.yaml
NA
GitHub Actions cancel all in-progress jobs if any matrix job fails.
This behavior makes investigating version-specific issues (e.g. #406)
harder.
> Build all variants like Travis CI

- runtime/runc_jailer.go
This commit addresses an issue with the fifo paths specified in the
machine config not being relative to the jailer's root path. This change
fixes this by making the path relative and running chown on those fifo
files
> Fixes bug with fifo files

- runtime/service_integ_test.go
It is actually working though.
NA
Adding a new test to make sure that OOM events are working.
> Test `/tasks/oom`

- firecracker-control/local.go
- runtime/service_integ_test.go
#409
We were not closing Unix abstract sockets on firecracker-local side,
which keeps the sockets alive. Clients cloud not create a new VM with
exact same identity.
In addition to that, firecracker-local now gurantees the absence of
a shim process, to make StopVM's contracts clear.
Fixes #409.
> Close all Unix abstract sockets correctly

- runtime/runc_jailer.go
- runtime/runc_jailer_test.go
Previously the basename part of a customer-supplied path is used
inside a jail directory.
However there is no guarantee that the supplied-path doesn't cause
a conflict against other paths (e.g. LogFifo vs. MetricsFifo) and/or
important system-reserved files (e.g. "kernel-image").
It is better to rename the files by ourselves rather than relying on
the customer-supplied paths.
> Rename the files inside a jail to avoid conflicts

- runtime/service_integ_test.go
- tools/docker/scripts/lsblk.sh
> Upgrade runc from 1.0-rc10 to 1.0-rc92

- Makefile
- runtime/service.go
- runtime/service_integ_test.go
- tools/image-builder/Makefile
This commit fixes a leak that occurs when an error has been encountered
in CreateVM
> Fix leak of VMs

- runtime/jailer_integ_test.go
- runtime/service_integ_test.go
> Run some subtests in parallel to make integ-test faster

- runtime/runc_jailer.go
unfortunately due to differences in arm, arm does not setup a cache
topology. This commit fixes that copying the system's cache topology
into the jailed rootfs
> Enables jailer to copy cache topology

- docs/quickstart.md
Most of the steps for installation, configuration and running of
firecracker containerd on rpm based linux distro is similar to debian.
Added an alternate quickstart script for Amazon Linux 2. Running on
a similar rpm based distro e.g. centos would need minimal changes.
For example instead of installing docker-ce using amazon-linux-extras,
it can be installed using yum install.
Signed-off-by: Alakesh Haloi <alakeshh@amazon.com>
> extend quickstart script to support rpm based distro

- internal/vm/vsock.go
tryConnect() has multiple error cases which would be difficult to
understand. This change adds some context on each of them.
> Wrap vsock-related errors to explain the context

- runtime/service_integ_test.go
Seems 20 seconds is too tight. This may not indicate a latency
regression. More developers we have, more tests we would run in
parallel during work hours.
> Adjust TestMultipleVMs_Isolated's timeout

- .buildkite/setup_al2.sh
On our Amazon Linux 2 BuildKite setup, we run all tests without Docker
to make the setup more closer to production. However runc uses `/run/runc`
directory that would cause a race condition if we have multiple builds
in parallel.
This change adds `--root` parameter to runc to avoid the race condition.
> Fix BuildKite's race condition on Amazon Linux

- runtime/service_integ_test.go
- tools/thinpool.sh
This PR has multiple test-related fixes. See the commit messages for the detail.
> Test fixes

- runtime/service.go
- runtime/service_integ_test.go
https://github.com/firecracker-microvm/firecracker-containerd/issues/492
a. Update go-sdk to have changes that implement DescribeInstanceInfo in sdk 
b. Modify StopVM to first check if instance is stopped and return error if it is, rather than hang trying to connect to agent..
> Fix for StopVM to force shutdown VM is in paused state in order to avoid hang

- internal/vm/dir.go
- internal/vm/dir_test.go
- runtime/jailer_integ_test.go
- runtime/service_integ_test.go
Remove the namespace directory descried in #488 
Change the directory structure to `[namespace#vmID/]`
Signed-off-by: Royce Zhao <qiqinzha@amazon.com>
> Remove namespace diretory

- .buildkite/setup_al2.sh
- docs/getting-started.md
- docs/quickstart.md
- tools/docker/entrypoint.sh
Updates all our docs/scripts/configs to use config version 2
> Use config version 2

- runtime/service_integ_test.go
The test was discarding an error from CreateVM when findProcess had
another error.
> Do not discard CreateVM's error

- .buildkite/al2_test.sh
- internal/vm/vsock.go
- internal/vm/vsock_test.go
- runtime/service_integ_test.go
This PR fixes multiple tap-related problems. I hope this could make TestMultipleVMs_Isolated stable...
> Fix tap-related test failures

- runtime/service.go
- runtime/service_integ_test.go
This commit doesn't fix the issue, but reproduce that in
TestStopVM_Isolated.
> Kill Firecracker forcefully if StopVM is hitting its context's timeout

- docs/design-approaches.md
- docs/shim-design.md
- firecracker-control/cmd/containerd/main.go
- runtime/README.md
Minor update to docs and comments for branch name references.
> doc: update branch name references

- docs/getting-started.md
- docs/quickstart.md
- go.mod
- go.sum
#587 
This PR makes the minimum required Go version consistent with the
version being tested in the pipeline.
> chore: update minimum required Go version

- runtime/service_integ_test.go
> Remove TestMultipleVMs_Isolated's timeout

- .buildkite/al2_pipeline.yml
- .buildkite/pipeline.yml
As like 69d69b1, this commit relaxes the timeout of slow tests.
> Allow each test to run for an hour at maximum instead of 10 minutes

- docker-credential-mmds/Makefile
- examples/Makefile
- snapshotter/Makefile
Minor changes to makefiles so cleanup is smooth. 
> fix: minor issues in makefiles

- docs/getting-started.md
- docs/host-file-isolation.md
- docs/logging.md
- docs/shim-design.md
Signed-off-by: Swagat Bora <swagatbora90@gmail.com>
*Issue #, if available:* Minor typo fix. There was an older PR #454 that never got closed
> Fix typo in getting-started doc

- docker-credential-mmds/README.md
> Add README for docker-credential-mmds

- runtime/service.go
#630
Only cleanup stub drives for tasks that have allocated them.
> fix: only cleanup allocated stub drives

- tools/docker/Dockerfile.integ-test
> Download critest earlier to speed up the build

- docs/remote-snapshotter-getting-started.md
- examples/cmd/remote-snapshotter/README.md
> Add remote snapshotter getting started guide

- .github/workflows/build.yaml
A bit improved github actions.
> Update gh actions

- .github/workflows/build.yaml
- agent/drive_handler.go
- config/config.go
- config/config_test.go
- docker-credential-mmds/mmds/client.go
- docker-credential-mmds/mmds/client_test.go
- docker-credential-mmds/mmds/helper_test.go
- examples/cmd/remote-snapshotter/go.mod
- examples/cmd/remote-snapshotter/go.sum
- examples/taskworkflow.go
- go.mod
- go.sum
- internal/bundle/bundle.go
- internal/fsutil.go
- internal/vm/ioproxy_test.go
- runtime/cni_integ_test.go
- runtime/drive_handler_test.go
- runtime/jailer_integ_test.go
- runtime/runc_jailer.go
- runtime/runc_jailer_test.go
- runtime/service_integ_test.go
- snapshotter/demux/proxy/address/http_resolver.go
> Upgrade containerd from 1.6.6 to 1.6.8

- volume/.gitignore
N/A
Add gitignore for volume package
> Add gitignore for volume package

- .github/workflows/build.yaml
Update actions/setup-go from v1 to v3.
> Update GitHub actions packages

- runtime/service.go
- runtime/service_integ_test.go
As like any other Linux processes, Firecracker could be terminated.
In this case, any requests that needs in-VM agent was returning
`ttrpc: closed: unknown` which was difficult to understand.
This change checks the existence of Firecracker before sending requests
to the in-VM agent.
Fixes #711
> Fail-fast if a VM is terminated

- internal/fsutil.go
- runtime/jailer_integ_test.go
- runtime/limits_integ_test.go
- runtime/service_integ_test.go
I started this pattern to save few characters, but it isn't really working when you have subtests.
> Don't reassign assert and require

- agent/service.go
N/A
Tracking a production issue which has the agent process dying as a result of a panic. This change is to enhance the agent logs by logging the request function name and task ID for each panic handler.
> Rework internal vm agent logs to include function and task id

- agent/service.go
N/A
Close fifoSet for the task and exec when the task is deleted.
> Use fifo close on task exec cleanup to prevent directory leak

- tools/image-builder/files_debootstrap/etc/systemd/system/firecracker-agent.service
This enabled debug logging for the in-vm agent.
> Enable debug logs in agent
