firecracker-microvm/firecracker-containerd

agent/service.go, runtime/service.go
It wasn't giving me the option to re-open #12 so I am just resubmitting it.  Please refer to #12 for discussion history. I copied over the two outstanding comments.
Monitor the state of a running container to enable clean shutdown of the
container and vm. Does this by adding a continuous monitor
goroutine that calls agent.State() once per second to see when the
container stops and initiate shutdown and publish the taskExit event.
=> Monitor state of a running container to cleanly shutdown

snapshotter/firecracker.go
When I run `go test` in snapshotter directory, executing `mkfs -t ext4 <file>` failed.
```
$ sudo -E env "PATH=$PATH" go test
~~
INFO[0000] building file system                          image=/tmp/snapshot-suite-Snapshotter-233656583/root/images/1
--- FAIL: TestSnapshotterSuite (0.00s)
--- FAIL: TestSnapshotterSuite/Basic (0.01s)
testsuite.go:142: failure reason: exit status 1
exec failed: mkfs -t ext4 /tmp/snapshot-suite-Snapshotter-453147216/root/images/1
github.com/firecracker-microvm/firecracker-containerd/snapshotter.run
/home/centos/firecracker-containerd/snapshotter/firecracker.go:430
github.com/firecracker-microvm/firecracker-containerd/snapshotter.(*Snapshotter).createImage
/home/centos/firecracker-containerd/snapshotter/firecracker.go:346 …
```
=> Add mkfs to force option

agent/main.go, agent/service.go, go.mod, go.sum
*Issue #, if available:*'
fixes #25 
- This implements graceful shutdown on agent side
- Minor code cleanup (we don't need `StartShim` on agent side)
How it was before:
- runtime calls agent.Shutdown
- agent calls runc.Shutdown (which calls os.Exit behind)
- runtime gets an error `connection closed` from agent.Shutdown
How it works now:
- runtime calls agent.Shutdown
- agent initiates graceful shutdown and responds OK to runtime
- agent shutdowns ttrpc and closes all connections
- agent calls runc.Shutdown (which calls os.Exit behind) and exits
- after agent exits, we need to call `reboot` in order to shutdown Firecracker VM properly. At this point we agreed with @nmeyerhans to use shell script wrapper.
By submitting this pull request, I confirm that my …
=> (More) Graceful Agent shutdown 

agent/service.go, go.mod, internal/common.go, runtime/service.go
Add stdio proxying from the container fifos to the agent, from the agent over
vsock to the runtime, and from the runtime to the fifo's specified by
containerd.
closes #17 
Proxies the stdout of the container over vsock to the runtime where it is re-written to the fifo's that containerd expects the output to be written.
Tested by running alpine /bin/sh and was able to use it interactively.
```
% sudo ./ctr run --runtime aws.firecracker --snapshotter firecracker-snapshotter docker.io/library/alpine:latest 2123 /bin/sh
ps
PID   USER     TIME  COMMAND
1 root      0:00 /bin/sh
6 root      0:00 ps
ls -al
total 16
drwxr-xr-x   18 root     root          1024 Nov 29 00:31 .
drwxr-xr-x   18 root     root          1024 Nov 29 00:31 ..
drwxr-xr-x …
```
=> Add stdio proxying between container, agent, runtime

snapshotter/Makefile
Naming the target naive clashes with the sub directory name and prevents
from the executable being built.
Use the actual file name so the make target check works.
=> snapshotter: Fix Makefile target

runtime/README.md
https://github.com/firecracker-microvm/firecracker-containerd/issues/57
Documentation
=> runtime: document the config file and its fields

go.mod, snapshotter/devmapper/devmapper.go, snapshotter/devmapper/devmapper_test.go, snapshotter/devmapper/metadata.go, snapshotter/devmapper/metadata_test.go, snapshotter/devmapper/pool_device.go, snapshotter/devmapper/pool_device_test.go, snapshotter/pkg/dmsetup/dmsetup.go
This PR implements metadata store for devmapper using `boltdb`
A few pros I see here:
- It's thread safe, so no worries about parallel calls to snapshotter
- Supports transactions, so metadata always in sync with `devmapper`
- Already used by `containerd`, so no new dependencies
=> Implement metadata store for devmapper

Makefile, agent/Makefile
In order to support a minimal microvm, e.g. based on Alpine, OpenWRT, or similar, we support the generation of a statically linked agent binary.
=> Support optional generation of a statically linked agent

.headers/go.txt, .headers/makefile.txt, CONTRIBUTING.md, Makefile
This will lint commit messages:
- DCO - require `signed off`
- dangling-whitespace - prevent dangling whitespaces on line endings
- short-subject - required <90 
Note: I've added `-range` flag since there are already a lot of invalid commit messages in master branch.
=> Validate commit messages and file headers

docs/getting-started.md
This makes changes to the getting started guide which reflected an older version of the package.
=> docs: Updating getting started guide to work with latest

snapshotter/devmapper/device_info.go, snapshotter/devmapper/metadata.go, snapshotter/devmapper/metadata_test.go, snapshotter/devmapper/pool_device.go, snapshotter/devmapper/pool_device_test.go, snapshotter/devmapper/snapshotter.go, snapshotter/pkg/dmsetup/dmsetup.go, snapshotter/pkg/losetup/losetup.go
https://github.com/firecracker-microvm/firecracker-containerd/issues/61
This PR adds device states instead of transactions and reworks device removal. 
=> Manage device states, rework device removal

internal/testutils.go, snapshotter/Makefile, snapshotter/devmapper/pool_device_test.go, snapshotter/devmapper/snapshotter_test.go, snapshotter/naive/naive_test.go, snapshotter/pkg/dmsetup/dmsetup_test.go, snapshotter/pkg/losetup/losetup_test.go
* Additional `go test` arguments can be specified with the `EXTRAGOARGS` make variable
* Tests which require root fail-fast instead of panicking, or can be skipped by setting the `DISABLE_ROOT_TESTS` environment variable.
<details>
<summary>fast-fail</summary>
```
$ make test EXTRAGOARGS='-v -count=1'
go test ./... -v -count=1
?   	github.com/firecracker-microvm/firecracker-containerd/snapshotter	[no test files]
?   	github.com/firecracker-microvm/firecracker-containerd/snapshotter/cmd/devmapper	[no test files]
?   	github.com/firecracker-microvm/firecracker-containerd/snapshotter/cmd/naive	[no test files]
=== RUN   TestLoadConfig
--- PASS: TestLoadConfig (0.00s)
=== RUN   TestLoadConfigInvalidPath
--- PASS: TestLoadConfigInvalidPath (0.00s)
=== RUN …
```
=> Snapshotter test improvements

snapshotter/naive/naive.go, snapshotter/naive/naive_test.go
naive: fix calculation for expected size
=> naive: fix calculation for expected size

Makefile
Small improvement in Makefile. `GOPATH` may not be defined as env variable (when default `~/go/` used). `go env GOPATH` handles this case.
=> Better GOPATH handling in Makefile

snapshotter/cmd/devmapper/main.go, snapshotter/cmd/devmapper/main_test.go, snapshotter/devmapper/config.go, snapshotter/devmapper/config_test.go, snapshotter/devmapper/pool_device.go, snapshotter/devmapper/pool_device_test.go, snapshotter/devmapper/snapshotter.go, snapshotter/devmapper/snapshotter_test.go
Address a few issues I got in `containerd` [PR](https://github.com/containerd/containerd/pull/3022) review:
- Resume base thin-device when snapshot creation failed
- Better check whether thin-device is active (all thin devices gets deactivated on reboot, so we can't rely on metadata)
- Snapshotter no longer creates or reloads thin-pool, just opens it or fails.
- Rollback thin device on error (#107)
/cc @sipsma
=> Snapshotter improvements

runtime/service.go
*Issue #, if available:* N/A
*Description of changes:* Added an error log when the task create request's options field cannot
be unmarshalled.
*Testing done:* `make clean && make STATIC_AGENT='true' && make examples && make lint` succeeds.
=> log task create options protobuf unmarshalling error.

go.mod, go.sum
Fixes https://github.com/firecracker-microvm/firecracker-containerd/issues/121
Updating the SDK is sufficient to work with Firecracker v0.15.0, though the quickstart guide no longer works and the getting started guide also needs to be updated; Firecracker's built-in seccomp enforcement is unhappy with glibc and needs to be built with musl libc.
I can either do the guide updates as part of this same PR or as a separate one; let me know which is preferred.
=> update to firecracker-go-sdk v0.15.0

snapshotter/README.md
When working on running our tests in a container, I encountered a bunch of strange race-conditions related to device node creation during the snapshotter tests. This turned out to be due to the udev daemon not being accessible inside the container even though I was bind-mounting /dev from the host to the container.
Another possible fix to this issue would be to change our snapshotter code to use the `--verifyudev` flag for all dmsetup operations. However, it turns out there is an environment variable `DM_DISABLE_UDEV` (documented on the lvm(8) man-page only, not dmsetup(8) man-page for some reason), that appears to be a catch-all for making dmsetup and other tools under the lvm umbrella behave well in an environment where udev is not …
=> Add note about DM_DISABLE_UDEV to README.

docs/quickstart.md
Fixes https://github.com/firecracker-microvm/firecracker-containerd/issues/127
Changes in dependencies cause firecracker-containerd to not build properly with Go < 1.11.4 (the go.sum digest algorithm changed slightly in that version).  Changes in Firecracker's seccomp enforcement and hard dependency on musl caused seccomp violations when built against glibc.
This change moves our quickstart guide to Debian, which has musl libc and an updated Go 1.11 >= 1.11.4 available in its repositories.
=> docs: update quickstart

snapshotter/cmd/devmapper/README.md
=> devmapper: remove incorrect documentation

docs/getting-started.md, docs/quickstart.md, runtime/README.md, runtime/config.go, runtime/config.json.example, runtime/service.go
The Firecracker API socket is important for the runtime, as it uses the socket to communicate with Firecracker.  Allowing the runtime to fully control the API socket (including its path) removes a potential failure condition from misconfiguration.
The API socket is hard-coded to exist within the current working directory.  Part of the contract that containerd exposes for runtimes is that they are started with the current working directory changed to be that of the OCI bundle.  Using an API socket in the OCI bundle makes its location well-known and predictable to the runtime.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> runtime: hard-code Firecracker API socket path

docs/getting-started.md, docs/quickstart.md, runtime/README.md, runtime/config.go, runtime/config_test.go
Sets default kernel arguments so that it is not required to specify.
=> runtime: specify default kernel arguments

Makefile
Travis (which runs this target) performs a shallow clone of the git repository at 50 commits.  Previously, a static commit SHA was specified, which has now become more than 50 commits in the past. This commit changes the git-validation line such that we only validate the most recent 20 commits.
=> lint: limit git-validation to 20 commits

docs/getting-started.md, docs/quickstart.md, runtime/README.md, runtime/config.json.example, tools/docker/firecracker-runtime.json
The console field was already removed, but stale documentation continued to reference it.  This commit removes the stale documentation.
=> runtime: remove "console" field from documentation

docs/getting-started.md, docs/quickstart.md, runtime/README.md, runtime/config.go, runtime/config_test.go
=> runtime: defaults for kernel and rootfs paths

docs/getting-started.md, docs/quickstart.md, runtime/README.md, runtime/config.go, runtime/config_test.go
Specify default CPU count as 1
=> runtime: default CPU count is 1

.buildkite/pipeline.yml, agent/Makefile, agent/service.go, agent/service_test.go
`cancelAll` would panic due to using `len(slice)` as an index.
=> agent: fixes panic on cancelAll function

snapshotter/devmapper/pool_device.go, snapshotter/devmapper/pool_device_test.go, snapshotter/devmapper/snapshotter.go, snapshotter/devmapper/snapshotter_test.go, snapshotter/pkg/dmsetup/dmsetup.go, snapshotter/pkg/dmsetup/dmsetup_test.go
This PR implements `Usage` for device mapper snapshotter.
It relies on the number of used blocks reported by `dmsetup status` command.
```
pool_device: 0 204800 thin-pool 0 13/25600 290/1600 - rw discard_passdown queue_if_no_space -
device3: 0 204800 thin 0 - <--- no file system
device2: 0 204800 thin 16128 204799 <---- just created with ext4 file system
device1: 0 204800 thin 18304 204799 <---- ext4 file system + 1 MB file
device1_snap: 0 204800 thin 20352 204799 <----- (parent device1) ext4 fs + 1 MB file from parent + 1 MB file extra (20352-18304)*512sectorSize/1024/1024=1MB
```
/ref https://github.com/containerd/containerd/pull/3022#issuecomment-475449586
/cc @cespo
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Implement usage for devmapper snapshotter

go.mod, go.sum, runtime/config.go, runtime/config.json.example, runtime/firecrackeroci/annotation.go, runtime/service.go, runtime/service_integ_test.go, runtime/service_test.go, tools/docker/naive-snapshotter/entrypoint.sh
1. This is the first half of the shim updates needed for running multiple containers per-VM. It consists of the host-side changes needed to group containers up into separate VMs by VMID. The second part of the updates are going to be VM-side in `agent`; they will be a separate PR from this one.
* Right now, multiple VMs can be spun up in parallel each with it's own container, but the above mentioned changes in `agent` will be needed to support multiple containers within each VM.
1. Many of the TODOs added will be removed by integrating with Max's fc-control plugin (#156).
1. There's a few small updates that will be needed to the shim design doc once this is approved; namely
* the use of just the `address` file instead of that plus the pid file (this is also what containerd has done in …
=> Group containers into different VMs by VMID

go.mod, go.sum
This is a workaround for some errors our build servers are hitting
when pulling down specific commits of /x/sys. It should not be
needed permanently.
=> Use explicit golang sys dependency.

.buildkite/logcheck.sh, .buildkite/pipeline.yml
The intent is to validate that all commits include a DCO (Signed-off-by) line,
and that no commits are "fixup" commits. This will run on pull requests and
will show up as a test failure if violations are found.
=> buildkite: add a git history validation step

runtime/service.go
This ensures that we capture logs from the firecracker-go-sdk libraries at the
expected verbosity level and to the expected output location.
=> runtime: pass logger to firecracker libraries

firecracker-control/local.go, firecracker-control/local_mock_test.go, firecracker-control/local_test.go, firecracker-control/service.go, proto/firecracker.pb.go, proto/firecracker.proto
This PR adds ability to query VM's context ID and combines `GetFifoPath`, `GetVMAddressResponse` and get CID in one `GetVMInfo` endpoint.
=> Implement get VM info endpoint

.gitignore, .gitmodules, Makefile, tools/docker/Dockerfile.runc-builder, tools/image-builder/.gitignore, tools/image-builder/Dockerfile.debian-image, tools/image-builder/Makefile, tools/image-builder/README.md, tools/image-builder/files_debootstrap/etc/hostname, tools/image-builder/files_debootstrap/etc/systemd/system/apt-daily-upgrade.timer, tools/image-builder/files_debootstrap/etc/systemd/system/apt-daily.timer, tools/image-builder/files_debootstrap/etc/systemd/system/container-rootfs.mount, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker-agent.service, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target.wants/container-rootfs.mount, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target.wants/firecracker-agent.service, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target.wants/getty.target, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target.wants/vsock-cli.service, tools/image-builder/files_debootstrap/etc/systemd/system/getty-static.service, tools/image-builder/files_debootstrap/etc/systemd/system/rom-dev.mount, tools/image-builder/files_debootstrap/etc/systemd/system/rom-overlay.mount, tools/image-builder/files_debootstrap/etc/systemd/system/rom.mount, tools/image-builder/files_debootstrap/etc/systemd/system/systemd-timesyncd.service, tools/image-builder/files_debootstrap/etc/systemd/system/vsock-cli.service, tools/image-builder/files_debootstrap/sbin/overlay-init
*Issue #75, #33*
This PR adds automation for creating MicroVM root fillesystem images. The images are created as *squashfs* files and configured to support read-only attachment with a read/write overlay layer on top. RunC and the firecracker-containerd agent are embedded in the image, and the agent is started by default. Per our current convention, the snapshotter-created container rootfs image is assumed to be on `vdb` and is mounted at `/container`.
If you have docker installed and configured in such a way as to allow you to run containers without root access, you can build an image with `make image` from the top level directory. The resulting image will be available as `image-builder/rootfs.img` See [README.md](image-builder/README.md) for more details.
In …
=> Add an image-builder component

firecracker-control/common.go, firecracker-control/helpers.go, firecracker-control/helpers_test.go, firecracker-control/local.go, firecracker-control/local_test.go
https://github.com/firecracker-microvm/firecracker-containerd/issues/159
- Use default configuration if some parameters weren't specified in create request.
I've reworked helpers to 'map or use defaults' instead of override logic.
- Small namespace fix when publishing stop event
=> Use default VM configuration if not specified in request

tools/docker/Dockerfile
There appears to have been an update pushed to either docker or buildkit that results in this line (which previously just did nothing) to fail. The `--chown` is not needed in the first place though so this change just removes it.
=> Skip unneeded chown when copying fc-agent.start.

agent/main.go, agent/service.go, go.sum, internal/vm/task.go, internal/vm/task_test.go, runtime/service.go, runtime/service_test.go
There are a few related changes being made here:
1. Give each ctx object a more specific name that indicates the scope of its
lifetime (i.e. one that will be canceled after a request or one that shuts
down the process).
2. Remove ctx when it's not needed for anything but logging; just use a pre-made
logger object instead
3. Use ctx to cancel requests where previously it was just ignored.
This is all spurred by the recently imported updates to TTRPC that resulted in
service method context objects to be canceled after the request is finished, but
the changes here seem beneficial besides that as its intended to make our use
of context more explicit and consistent.
By submitting this pull request, I confirm that my contribution is made under the …
=> Cleanup use of context objects throughout the code.

firecracker-control/vsock.go
sysCall was not being used other than in tests. However, since we never actually called the sysCall function, the tests would use syscall.Syscall instead
=> firecracker-control: linter was complaining about sysCall not being used

docs/host-file-isolation.md
Add a new design document on ensuring that host files remain isolated
between multiple microVMs.
=> docs: Host file isolation

.golangci.yml, Makefile
Some tests require spaces at the end of strings for proper string
comparison
The linter, git-validation, checks more than just commit messages, but the actual diff that is going to be merge. And if there are any danglers, it'll error out.
=> dangling whitespace linter isn't friendly with tests

Makefile, tools/docker/Dockerfile
Following up on #153, this change eliminates duplication of runc builds. It does this by eliminating the `runc-build` target in `tools/docker/Dockerfile`, which would clone the runc git repository and build the binary during image creation, in favor of a discrete containerized build step using the runc submodule in the top-level makefile.
=> Runc build cleanup

examples/taskworkflow.go, firecracker-control/client/client.go, firecracker-control/local.go
This PR adds a helper TTRPC client for the firecracker service (original discussion  https://github.com/firecracker-microvm/firecracker-containerd/pull/196#discussion_r290807527)
Also now closing a connection after its no longer needed.
=> Add TTRPC client helper

.buildkite/pipeline.yml
This actually makes some steps be required to be sequential. The steps
that were used to be ran sequentially was determined by whether or not
they used the naive snapshotter
=> Fixing CI to run sequentially

agent/main.go, tools/docker/fc-agent.start, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker-agent.service
Minor cleanup: `id` command line flag is no longer used, so no reason to require it. 
=> Remove ID flag from Agent

agent/main.go, agent/service.go, internal/vm/task.go, internal/vm/task_test.go, runtime/service.go
The new runc service implementation supports managing multiple tasks in a single
service. This upgrade thus allows us to use a single task service instantiation
instead of 1-per-task, which in turn helps simplify our internal task manager
implementation.
**NOTE:** This change stands on its own, but the primary motivation for doing it now is that it ends up simplifying a lot of the code for exec support, which I'm in the process of finalizing.
=> Upgrade to v2 runc service in VM Agent.

runtime/service_integ_test.go
If an integration test fails with a non-zero exit code, we should log
what error occurred
=> runtime: Add error messages in integration test failures

runtime/service_integ_test.go
Previous integration tests would call wait before start on a new task,
but the stub integ test did start and then wait, which may have
completed by the time wait was called. This would result in an error on
wait.
=> runtime: Fix integration test by calling wait before start

agent/service.go, firecracker-control/local.go, internal/vm/dir.go, internal/vm/dir_test.go, runtime/service.go, runtime/service_test.go
https://github.com/firecracker-microvm/firecracker-containerd/issues/195
This PR validates path-related identifiers (VM IDs, container IDs and namespaces).
=> Enforce ID validation

agent/error.go, agent/error_test.go, agent/service.go, internal/bundle/bundle.go
Firecracker requires some time to populate the config space change which
was causing failures in our CI due to calling patch drive followed by
an immediate call of mounting that drive.
https://github.com/firecracker-microvm/firecracker/issues/1159#issuecomment-507984468
Fixes #214
=> agent: Adding retry around mounting logic

runtime/service.go, runtime/service_test.go
Prior to this change the config fields of 'Debug' and 'LogLevel' were
not used and did not set the proper debug level during logging.
=> runtime: Adding support of setting log levels thru config

docs/getting-started.md, go.mod, go.sum
This PR updates getting started guide with info about containerd's default labels.
It allows to specify `--runtime` and `--snapshotter` flags just once when creating a namespace (or add labels to an existing one), and then just use `ctr` without these params.
ref: https://github.com/containerd/containerd/pull/3403
=> Update getting started

docs/getting-started.md, docs/quickstart.md, firecracker-control/cmd/containerd/Makefile, runtime/README.md, tools/docker/Dockerfile
The commits here:
* Build a `firecracker-ctr` binary from the same version of our `firecracker-containerd` binary to ensure the two are at compatible versions. The docs are updated to specify use of `firecracker-ctr` over plain `ctr`.
* Specify in the docs that Firecracker needs to be built from the 0.17.0 tag, which we recently updated to use.
As discussed elsewhere, I originally attempted to build the `firecracker-ctr` binary by adding `containerd` as a submodule and put a replace directive in our go.mod file pointing to the submodule. This actually worked but was extremely ugly as use of the replace directive requires that the replacement directory have a go.mod file, which in turn requires us to run `go mod init` in our containerd submodule, which itself had other side effects, etc. …
=> Sync quickstart and getting-started docs

Makefile, runtime/Makefile
Before this, the runtime integ-test target would only be marked as failed if
the last test failed.
I also included a separate commit here fixing a typo from #227 where the top-level integ-test target used the wrong dependency name.
=>  Fail runtime integ-test if any single test fails. 

runtime/drive_handler.go
None
newStubDriveHandler is not passing the logger, while it is taking.
(wouldn't it be caught by static analysis?)
=> Pass the logger to a new stubDriveHandler correctly

runtime/service.go, runtime/service_integ_test.go
#65
While we cannot repro #65 anymore, we'd like to have some tests to
prevent regression.
=> Make sure containers are deleted correctly

runtime/service.go
Use "id", "exec_id" and "vmID" consistently.
None
Some methods used "containerID", "TaskID" and/or "ExecID"
=> Set log fields consistently

runtime/service_integ_test.go, tools/docker/Dockerfile, tools/docker/scripts/lsblk.sh
#203
This change introduces our own lsblk(8) equivalent, which makes
the integration test distro-agonostic and be able to run without
util-linux.
Fixes #203.
=> Make integration tests distro-agnostic

tools/docker/Dockerfile
NA
COPY will invalidate caches based on the contents' checksums.
Executing RUN before COPY may make builds faster.
=> Download default-vmlinux.bin before COPY

runtime/service_integ_test.go
None
Alpine is smaller than Debian that would be faster to pull from the internet.
Pros:
- It might make our tests faster, in theory.
Cons:
- Assuming developers use Debian (I use, because of https://github.com/firecracker-microvm/firecracker-containerd/blob/master/docs/quickstart.md), the subtle difference between Debian and Alpine would be sometimes annoying.
=> [RFC] Use Alpine Linux instead of Debian GNU/Linux

runtime/service.go
#210
Regarding ConnectResponse, we can return shim_pid, but cannot return
task_pid as the way that clients can interact with.
Instead, we'd like to return ErrNotImplemented to tell them that we
cannot provide what they expect.
=> Don't return PIDs inside micro VMs

Makefile
None
eventbridge/Makefile is mostly empty for common tasks such as "all" or
"integ-test", but "test" runs go test, which should be trigged by
"make test" on the root directory.
=> Include eventbridge on "make test"

runtime/service.go, runtime/service_test.go
Related to, but may need more changes to actually fix #230
Currently the drive handler knows non-stub drives (root drive). Because of that PatchStubDrive() replace non-stub drives, once all stub drives are patched.
=> Don't patch non-stub drives

go.mod, go.sum
A couple other dependencies got updated as when running
```
go mod download && go mod tidy
```
=> Update to use v0.17.0 of the Firecracker Go SDK

docs/networking.md
For those who reviewed this previously, the final doc in this PR has a few minor tweaks other than grammar/spelling fixes:
1. I did a rough first-pass implementation of everything (code is [here](https://github.com/sipsma/firecracker-containerd/commits/cni) and [here](https://github.com/sipsma/firecracker-go-sdk/commits/cni)). The only update that resulted was that the CNI configuration API needs to take a NetworkName in addition to a CNI bin path and CNI conf path. If anything else gets modified as the implementation progresses I will update the doc too.
2. Sanitized a few links to internal code repos; added links to Kata Containers and Ignite where their prior art is referenced
3. Cleaned up the Performance Numbers section. I'm indicating …
=> Add networking doc proposing CNI integration.

runtime/drive_handler.go, runtime/drive_handler_test.go, runtime/service.go, runtime/service_integ_test.go, runtime/service_test.go
Related, but doesn't fix #243
While we don't support the use-case right now, the error message
regarding the lack of free stub drives should be clear for customers.
This change also cleans up drive_handler.go.
=> Make sure the error message regarding stub drives is clear

runtime/Makefile, tools/docker/Dockerfile
Docker no longer uses /dev/init as init. So, we can use --init instead
of installing our own tini binary.
=> Use docker's --init as is

README.md
NA
Building a Go plugin is hard.
=> Explain why do we need to have our own containerd binary

.gitmodules, Makefile, tools/docker/Dockerfile, tools/docker/Dockerfile.firecracker-builder
This is intended to ease development with Firecracker and version upgrades.
Note this does not upgrade Firecracker to a new version ( ref #259 ), it keeps the version at 0.17 for now, but it should make moving to 0.18 easier.
=> Build firecracker from a submodule.

Makefile, agent/main.go, docs/getting-started.md, docs/quickstart.md, examples/Makefile, go.mod, go.sum, internal/common.go, internal/vm/dir.go, internal/vm/vsock.go, runtime/service.go, runtime/service_integ_test.go, runtime/service_test.go, tools/docker/Dockerfile.firecracker-builder
This consists of:
* Upgrading to the new Go SDK version.
* Using the new vsock interface with unix-domain socket backend on the host.
Closes #259 
=> Upgrade to Firecracker v0.18.0.

firecracker-control/cmd/containerd/main.go
containerd needs at least one snapshotter to be registered.
Otherwise dependent services will fail to register:
```
INFO[2019-09-26T18:20:47.828960162Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2019-09-26T18:20:47.828993788Z] failed to load plugin io.containerd.metadata.v1.bolt  error="no plugins registered for io.containerd.snapshotter.v1: not found"
INFO[2019-09-26T18:20:47.829017391Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
WARN[2019-09-26T18:20:47.829031956Z] failed to load plugin io.containerd.differ.v1.walking  error="no plugins registered for io.containerd.snapshotter.v1: not found"
INFO[2019-09-26T18:20:47.829046365Z] loading plugin "io.containerd.gc.v1.scheduler"... …
```
=> Fix containerd binary

firecracker-control/local.go, internal/vm/dir.go, internal/vm/dir_test.go, runtime/service.go, runtime/service_integ_test.go, runtime/service_test.go
This limits their length which prevents us from exceeding the max socket
length limit imposed by Linux.
Closes #264
=> Specify unix socket paths as relative paths.

Makefile
PWD is an env var, which can be unset in many scenarios (such as when a command
is prefixed with sudo without "-E"), which in turn can lead to confusing
failures when running make commands. CURDIR is set by make and avoids those
issues.
=> Use CURDIR instead of PWD in Makefile.

tools/image-builder/README.md
While debugging something with a user, they ended up with a VM rootfs that did
not have the agent binary due to not building the agent bin before building the
rootfs. This change clarifies the image-builder docs to help ensure that
situation doesn't happen.
Tested the changes by manually building a rootfs w/ docker using the instructions in the doc. `make image` is also already tested in our CI system.
=> Clarify image-builder docs to ensure agent+runc are pre-built.

Makefile, docs/getting-started.md, tools/demo/fcnet.conflist
Fixes #265 
Also included a separate small commit to remove some outdated instructions in the getting-started guide that I noticed while working on this.
Tested by running the quickstart guide on a new `m5d.metal` w/ Debian Stretch and verifying I by default got internet access from firecracker-containerd containers even when the host had pre-existing Docker iptables rules.
=> Add firewall plugin to demo-network configuration.

go.mod, go.sum, internal/Makefile, internal/cmd/test-bridged-tap/main.go, internal/psutil.go, runtime/Makefile, runtime/cni_integ_test.go, runtime/service_integ_test.go, tools/docker/Dockerfile
The intention of this test case is to add basic support for running performance
tests of various network configurations and to get a comparison of the CPU usage
differences between a TC-based VM network and a bridge-based VM network.
The test case added tries to make as fair a comparison as possible between TC
and a bridge. The TC approach uses the tc-redirect-tap CNI plugin, which results
in the following network layout for each VM:
[iperf server] <- vethA <- vethB <- [tc mirror] <- tap0 <- [iperf client]
In order to get a fair comparison, we want to run a bridge-based test with the
following layout:
[iperf server] <- vethA <- vethB <- [bridge] <- tap0 <- [iperf client]
Unfortunately, existing bridge based plugins usable in a general purpose test
like this cannot setup a bridge with a …
=> Add performance test case comparing tc w/ bridge.

docs/drive-mounts-proposal.md
For those who have reviewed previous versions of this doc, I've made some changes to the API in order to replace the pre-existing `AdditionalDrives` field rather than supplement it. This seems to result in a cleaner overall API at the expense of backwards-incompatibility (though it should be trivial for consumers to update). The actual substance of the proposal+implementation is the same though.
=> Add doc proposing support for mounting drives inside VM.

runtime/main.go
By default, containerd shim code results in our shim process being a subreaper
and running a reaper loop that waits on any children when SIGCHLD signals are
delivered. This does not work for us because we have code that uses "os/exec" to
spawn child processes (in the go sdk specifically). When "os/exec" waits on
child processes, it is in a race with the reaper loop, causing occasional
"wait: no child processes" errors when running commands.
Fixes #285 
Unfortunately, there aren't really any good ways to test this that aren't incredibly contrived. The only way I could get the error to occur consistently was changing the code to spawn tons of child processes, which we obviously don't want to do in actual merged code. I manually tested this …
=> Disable setting the shim as a subreaper and a reaper.

.buildkite/pipeline.yml
image-builder may fail cleanup if a job has been cancelled. To fix this
we will manually run make clean at the end of every CI job.
=> Adds cleanup step for CI

runtime/cni_integ_test.go, runtime/service_integ_test.go, tools/docker/Dockerfile, tools/docker/firecracker-runtime-defaultnetwork.json
TestAutomaticCNISupport is the only test which requires a runtime config
that has a list of default network interfaces. This change results in
that test being the only one to use such a runtime config, which allows
other tests to optionally not use any network interfaces if required.
In general, I think a better model will be for tests to just each generate this runtime config themselves instead of using a set of static ones copied into the docker image (using some helper methods). I [created an issue](https://github.com/firecracker-microvm/firecracker-containerd/issues/291) for implementing this, but the change in this PR will …
=> Only use runtime config w/ default network ifaces in one test.

runtime/drive_handler_test.go
This commit changes to use ioutil.TempDir as opposed to creating a
static directory when running the TestStubDriveHandler.
=> Makes use of ioutil.TempDir in stub drive tests

.buildkite/hooks/pre-exit, .buildkite/pipeline.yml
This commit removes the cleanup step from the pipeline.yml file and
instead adds a hook that allows for cleanup to always occur even in the
event of a cancel.
The `pipeline.yml` cleanup only occurs if you let the whole job finish, which is not what we want.
=> Add pre-exit hook to cleanup after job

internal/vm/dir.go, internal/vm/dir_test.go
NA
This test didn't work on my box and I figured out why...
=> Unit tests shouldn't assume that a certain directory is present

tools/docker/Dockerfile
This changes fixes the Dockerfile as tools/docker/naive-snapshotter no
longer exists
=> Fixes Dockerfile

runtime/integ_test.go, runtime/noop_jailer.go, runtime/runc_jailer.go
It would improve the situation described on #128, but it may not be enough to resolve the issue.
The log is pretty noisy but may be useful for debugging.
=> Connect stdout/stderr of Firecracker in Debug mode

docs/getting-started.md
Signed-off-by: Cody Roseborough <cdr@amazon.com>
*Issue #, if available:* #194 
Modifies the getting started guide to use dev-mapper snapshotter instead of the naive snapshotter.
=> Modify getting-started to use devmapper snapshottter

Makefile, proto/Makefile, tools/docker/Dockerfile.proto-builder
Makes it so that running `make proto` from the root of the project
compiles the protos in a docker container defined in
tools/docker/Docker.proto-builder. This image is build as part of `make
deps`.
This changes the default behavior but the previous behavior is still available by running `make proto` in the proto/ dir.
Signed-off-by: Cody Roseborough <cdr@amazon.com>
=> Move proto compiling to a container

.travis.yml, go.mod, go.sum, tools/docker/Dockerfile, tools/docker/Dockerfile.proto-builder, tools/docker/Dockerfile.runc-builder
- Add go1.13 as a build target for travis.
- Set the go version in go.mod at 1.11.
- Update a line in go.mod that wasn't compliant with the more stringent
validation in 1.13.
- Update Dockerfiles to use 1.13.
See [here](https://tip.golang.org/doc/go1.13#version-validation) for information on the version validation. The error I was seeing was:
```go: github.com/firecracker-microvm/firecracker-go-sdk@v0.17.1-0.20191030150325-dbf9a1e05f090: invalid pseudo-version: revision is longer than canonical (dbf9a1e05f09)```
This seems to be happening b/c the git prefix was 1 char to long (13 instead of 12).
Signed-off-by: Cody Roseborough <cdr@amazon.com>
=> Update to go1.13

firecracker-control/cmd/containerd/.gitignore
=> firecracker-control: ignore firecracker-ctr binary

runtime/runc_jailer.go, runtime/runc_jailer_test.go
While most of them are harmless to have, it may be better to keep files less readable/writable when we can.
=> Fine-tune runc-related permissions

runtime/service_integ_test.go, tools/docker/Dockerfile, tools/image-builder/Makefile, tools/image-builder/README.md, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target.wants/haveged.service, tools/image-builder/files_debootstrap/etc/systemd/system/haveged.service
haveged ensures that there is sufficient entropy available to processes running
within the microvm. Without sufficient entropy, it is fairly easy for processes
to get blocked on reading /dev/random or making getrandom() syscalls, including
during boot (which can result in CreateVM calls to fail if the agent process
gets blocked).
haveged was chosen as it enforces no minimum kernel requirements, does not
add CPU requirements (i.e. existence of RDRAND or similar instructions) and is
currently used by Debian for related use cases such as seeding entropy in their
installer.
One other option was "rngd", which has versions that support use of RDRAND.
It was not chosen as RDRAND is not universally trusted or portable. Similarly,
use of the "random.trust_cpu=on" kernel boot parameter was ruled …
=> Add haveged to image-builder's rootfs.

runtime/integ_test.go, runtime/service.go, tools/docker/entrypoint.sh, tools/image-builder/files_debootstrap/sbin/overlay-init
NA
Miscellaneous changes to improve log messages.
=> Declutter logs

.golangci.yml, .travis.yml, runtime/service_integ_test.go
"make" doesn't compile *_test.go, but "make test" does.
121afa34449077eef99e533712d2a3cce501612a introduced
ProcessState.ExitCode which is not available in Go 1.11.
=> Run "make test" on Travis CI

runtime/integ_test.go, runtime/limits_integ_test.go, tools/docker/entrypoint.sh
NA
This change adds integration tests that verify in-container workloads
are restricted correctly.
=> Test that the size of a root drive is capped 

runtime/service_integ_test.go
The exit code is in MSB. Not so sure why it was working on #330
itself's BuildKite check though.
=> Fix exitCode()

firecracker-control/local.go, go.mod, go.sum, runtime/service.go, runtime/service_integ_test.go, tools/image-builder/Dockerfile.debian-image, tools/image-builder/Makefile, tools/image-builder/files_debootstrap/etc/systemd/system/firecracker-agent.service, tools/image-builder/files_debootstrap/sbin/overlay-init
NA
- On rootfs side, we `reboot(2)` after the successful completion of VM agent. That allow us to not killing Firecracker
- On firecracker-contol, `os.RemoveAll()` is added to simplify shim. Since firecracker-control is responsible for creating a shim directory, corresponding removal should be happening on there as well.
- On runtime, `Shutdown()` is now waiting the completion of the VMM process and not killing Firecracker if possible.
=> Cleanup around Shutdown() and StopVM() 

Makefile, examples/Makefile, runtime/Makefile, runtime/drive_handler_test.go, runtime/runc_jailer_test.go, tools/docker/Dockerfile.integ-test
#313
As described in #313, firecracker-containerd-integ-test is copying the entire source directory to the container in the very early stage, which makes incremental build slower. This PR changes the strategy to
- Build binaries without Docker
- Copy the binaries to a Docker image later
- Only use go.mod and go.sum to download dependencies inside a container
That will make incremental build much faster.
=> Create a small Docker image for running integration tests

.buildkite/pipeline.yml
Integration tests seem having some issues, and took hours sometimes.
While we should fix the root cause, this change makes the issues less
severe.
Here are some bad builds we had recently:
* https://buildkite.com/firecracker-microvm/firecracker-containerd/builds/1123
* https://buildkite.com/firecracker-microvm/firecracker-containerd/builds/1122
* https://buildkite.com/firecracker-microvm/firecracker-containerd/builds/1121
* https://buildkite.com/firecracker-microvm/firecracker-containerd/builds/1166
=> Cancel integration tests that take more than 10 minutes

runtime/Makefile
It would make running a failed test slightly straightforward, while
it was technically possible by passing INTEG_TEST_SUFFIX though.
=> Define each isolated test as a standalone Makefile target

Makefile, go.mod
This is beneficial in that it removes another hard dependency on the host's
version of go. It also might prevent an issue I saw this morning in buildkite
where builds that previously passed started failing when compiling a third-party
dependency during the call to "cni-bins". The build was using the host's GOPATH
(not the docker volume gocache) and go version and I was only able to fix it by
manually logging into the host and clearing out the GOPATH directory.
=> Build cni-bins in docker.

Makefile
The agent is still built with host Go, which is sometimes quite old.
=> Build Agent in Docker

Makefile, agent/main.go, firecracker-control/local.go, runtime/service.go, runtime/service_integ_test.go, tools/docker/Dockerfile.integ-test, tools/image-builder/Makefile
#247 
There are three commits in this PR
* Add a rootfs to simulate the situation: Not so sure this is the best way though.
* Remove errors.Wrap from firecracker-control: Shim is more aware about errors and fc-control should be act as a transparent proxy. We should remove all of errrors.Wrap from this layer and let shim decide errors.
* Actually fix the issue.
=> Returns codes.DeadlineExceeded when we forcebily kill a VM

agent/drive_handler.go, proto/service/drivemount/drivemount.proto, proto/service/drivemount/ttrpc/drivemount.pb.go, runtime/drive_handler.go, runtime/drive_handler_test.go, runtime/service.go, runtime/service_integ_test.go
Issue #243 
Added possibility to reuse stub drives of just deleted containers:
- The `Unmount()` method was added to `agent/drive_handler` to support unmounting used stub drives.
- The `Release()` method was added to aggregate all steps we need to release used stub.
- Modified task `Delete()` method to use new `Release()` method.
=> Support for container stub drive reuse

.buildkite/pipeline.yml, Makefile, go.mod, go.sum, proto/Makefile, proto/firecracker.pb.go
I noticed our go.mod/go.sum and generated proto defs were a bit out of sync (the proto differences were very minor, just differences in the comments of a .pb.go), so figured it was a good time to add some verification steps to buildkite that check if go.mod/go.sum and the proto defs are all up to date.
Closes #323 
Verified the steps fail as expected w/ a purposely broken commit here: https://buildkite.com/firecracker-microvm/sipsma-firecracker-containerd/builds/861#
=> Add extra verify steps to buildkite for go.mod/go.sum and proto defs

.buildkite/pipeline.yml, runtime/Makefile, runtime/service_integ_test.go
*Issue #343 *
Added possibility to increase number of VM's through buildkite for TestMultipleVMs_Isolated.
=> Added possibility to change number of vm's for MultipleVmsTest

.buildkite/pipeline.yml, agent/main.go, examples/etc/containerd/firecracker-runtime.json, runtime/service.go, runtime/service_integ_test.go
There's a few related cleanups here:
1. Fix an issue where the timeout used for Shutdown calls (as opposed to StopVM
calls) was too long due to multiplying by time.Second twice.
2. Don't rely on the error type being exec.ExitError to determine if StopVMM
needs to be called. This didn't work because the Go SDK wraps error types
returned by machine.Wait(). The new logic eliminates the need for this check.
3. Expose monitorVMExit's knowledge of when the VM exits via a field, which
allows shutdown to just read that field instead of making its own separate
Wait call. This dedupes some logs and simplifies the shutdown function a bit.
Overall, the code related to shutdown is still pretty convoluted. The
complication is mostly due to the fact that we are given multiple contexts by
containerd shim …
=> Fix shutdown logic.

agent/agent_test.go, agent/service.go
While debugging something else I realized the current logic for generating a
unique id from a given (taskID, execID) pair has a silly corner case where
different pairs result in the same id:
* taskID="task-task", execID="task" results in "exec-task-task-task-task"
* taskID="task", execID="task-task" also results in "exec-task-task-task-task"
This change uses the fact that the IDs are earlier validated with containerd's
identifier validation logic (which bans use of "/" in the ID) to make a unique
ID by using "/" as a separator and then doing a base64 encode (to keep the id
filesystem safe).
I noticed this while looking into #363. I don't think it has anything to do with that issue but it's worth fixing anyways.
By submitting this pull …
=> Fix corner case in agent's taskExecID.

Makefile, docs/getting-started.md, tools/demo/fc-br0.interface, tools/demo/fcnet.conflist
Previously our CNI-based demo network used the ptp CNI plugin to configure
point-to-point connectivity between the container VMs and the host.  This
change uses the bridge plugin instead, which facilitates direct communication
between container VMs via the bridge interface.  The justification for this is
that inter-container connectivity can be useful from a deployment point of
view, but also makes for a more interesting demo.
Production deployments should, of course, configure their networking based on
local requirements, which includes taking task isolation into account as
appropriate.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Use bridge networking in the demo-network configuration

runtime/cni_integ_test.go, runtime/integ_test.go, runtime/jailer_integ_test.go, runtime/service_integ_test.go
While the functionality is working, I'd like to have more tests with jailer-enabled.
=> Test StopVM() with Jailer just in case

client/client.go
Some container orchestrators need to how firecracker-containerd uses
microVMs, especially the layout of key directories.
The client package is designed to expose the layout, without exposing
the implementation details too much.
=> Add "client" package for container orchestrators

runtime/service.go, runtime/service_integ_test.go
Apparently clients are unable to receive /firecracker-vm/stop
correctly.
=> Fix `/firecracker-vm/stop` event

go.mod, go.sum
Fixes #363
Upgrade containerd from 1.3.1 to 1.3.3. The new version includes fixes @sipsma made!
=> Upgrade containerd from 1.3.1 to 1.3.3

runtime/cni_integ_test.go
This was originally in #383, but since the PR has been open for 2+ weeks. I'd like to merge changes that we can have, to make the PR smaller.
The `err` is unnecessary shared by multiple goroutines.
=> Don't share `err` between multiple goroutines

go.mod, runtime/jailer.go, runtime/noop_jailer.go, runtime/runc_jailer.go, runtime/service.go, runtime/service_integ_test.go
The jailer will leave containers behind if the jailing process was
killed with SIGKILL.
=> Jailer leaves containers behind

go.mod, go.sum, runtime/drive_handler_test.go, runtime/jailer.go, runtime/noop_jailer.go, runtime/runc_jailer.go, runtime/service.go, runtime/service_integ_test.go
NA
This PR makes StopVM() synchronous. We initially thought StopVM() should be asynchronous, and eventing should be used for synchronization, however
- CreateVM() is already synchronous. It waits the establishment of the vsock connection and guarantees that a VM is usable at the end of the request.
- StopVM() was somewhat synchronous even before this change. Since #362, StopVM() was waiting `<-s.shimCtx.Done()` before returning a response. So latency impact of this change is pretty minimal.
- It makes clients' life easier. Container orchestrators may create resources (e.g. filesystem images) before creating a VM. Then removing the resources must be happening after StopVM(). Doing synchronization inside StopVM() would make orchestrators's …
=> Make StopVM() synchronous

.buildkite/al2env.sh, .buildkite/setup_al2.sh, Makefile, internal/vm/vsock.go, runtime/service_integ_test.go, tools/docker/Dockerfile.firecracker-builder, tools/docker/scripts/lsblk.sh
Fixes #253 finally!
Upgrade Firecracker to v0.20.0
=> Upgrade Firecracker to post-v0.20.0

.buildkite/al2_pipeline.yml, .buildkite/al2_test.sh, .buildkite/pipeline.yml, examples/Makefile, runtime/Makefile, runtime/cni_integ_test.go, runtime/integ_test.go, runtime/jailer_integ_test.go, runtime/limits_integ_test.go, runtime/service_integ_test.go, tools/docker/Dockerfile.integ-test, tools/docker/entrypoint.sh, tools/thinpool.sh
On both "Getting Started" and "Quickstart", we explain the way to configure devmapper with loopback devices, but thinpool.sh assumes that a thinpool is backed by LVM.
Make thinpool.sh work with loopback devices. Also remove snapshotter-related environment variables and if's.
=> Make integration tests work with loopback devices

.buildkite/al2_pipeline.yml, .buildkite/al2_test.sh
NA, but it will fix "Warning: This log has exceeded the 1MB display limit. Below we are only showing the last 1MB of output." on https://buildkite.com/firecracker-microvm/firecracker-containerd-al2/builds/177#1e4dc126-d811-4e4f-b6af-d3ffbbe6b432
As like the Docker-based build, keep logs under runtime/logs.
=> Redirect firecrakcer-containerd's logs to runtime/logs/containerd.out

Makefile
The host may have a value defined for GOPROXY that should still be respected inside containers used for building Go programs.
=> makefile: use host GOPROXY value for %-in-docker

docs/scaling.md
I have put together a set of guidelines to configure the host OS to scale the number of microVMs past one thousand (tested with 1500 microVMs on a host with 256GB memory). Feedback is welcome.
=> Added guidelines for scaling firecracker VMs count

runtime/Makefile, runtime/benchmark_test.go, runtime/integ_test.go
NA
Benchmark CreateVM and StopVM.
Things I'd like to discuss;
- I'm running both CreateVM and StopVM inside the loop, mainly because it makes running them under Go's benchmark library easier, but it is not ideal.
- Moreover, should we use Go's benchmark library? We may want to know p50, p90, p100, ...
=> Benchmark CreateVM and StopVM

.github/workflows/build.yaml
We are pretty happy about Travis CI, but GitHub Actions are
- Available as hosted and self-hosted. We could use GitHub Actions to
replace both Travis CI and BuildKite.
- Well integrated with GitHub. We can reduce accounts/credentials we
need to worry about.
=> Use GitHub Actions

examples/taskworkflow.go, examples/taskworkflow.md, runtime/service_integ_test.go, tools/docker/Dockerfile.integ-test, tools/docker/config.toml
*Issue #387 *
Socket name was aligned with the quickstart guidelines. Removed the `-mask` argument from the readme as it is not supported anymore. Specified that `-ip` argument requires CIDR and not just an IP address.
Signed-off-by: Dmitrii Ustiugov <dmitrii.ustiugov@ed.ac.uk>
=> Updated taskworkflow.go: fixes in socket name and readme.

.buildkite/al2_pipeline.yml, .buildkite/pipeline.yml, Makefile, docs/quickstart.md
NA
Use Debian 10 (buster) instead of Debian 9, since it is available on AWS Marketplace 🎉 
=> Use Debian 10 (buster) on quickstart.md and as Docker images' variants

go.mod, go.sum
NA
Upgrade containerd from 1.3.3 to 1.3.4 to include some fixes.
=> Upgrade containerd from 1.3.3 to 1.3.4

runtime/service.go, runtime/service_integ_test.go
GetVMInfo already had the CgroupPath field, but it looks like it was
never set. This commit sets the cgroup path if the jailer is a
cgroupPather.
Fixes #416 
=> Set cgroup path when calling GetVMInfo

agent/service.go, internal/vm/fifo.go, internal/vm/ioproxy.go, internal/vm/ioproxy_test.go, internal/vm/task.go, runtime/service.go, runtime/service_integ_test.go
NA
* The first commit reproduces the issue
* The second commit fixes the issue. Opening a FIFO with O_RDWR is unnecessary and makes EOF invisible.
* The third commit fixes a timing issue. Closing all connectors by the cancellation of the passed context seems too early. We need to copy bytes even after the end of the process, since a pipe can buffer some bytes.
=> Fix Exec()'s timeout issue

runtime/jailer_integ_test.go, runtime/noop_jailer.go, runtime/runc_jailer.go, runtime/service.go, runtime/service_integ_test.go
Previously the cleanup logic is in firecracker-control, but it doesn't
work correctly with a runc-based jailer, since the jailer is making
files without namespaces.
Morever the cleanup logic is running after StopVM() that makes our
contracts unclear. We should guarantee all resource are deleted at
the end of StopVM().
#415
=> Remove a shim directory on StopVM() correctly and synchronously

go.mod, go.sum
NA
This change upgrades containerd to post-1.3.4 for including
https://github.com/containerd/containerd/pull/4195.
=> Upgrade containerd to post-1.3.4

config/config.go, config/config.json.example, docs/logging.md, examples/etc/containerd/firecracker-runtime.json, internal/debug/debug.go, internal/debug/debug_test.go, internal/debug/error.go, runtime/integ_test.go, runtime/noop_jailer.go, runtime/runc_jailer.go, runtime/service.go, runtime/service_test.go
This adds the debug package and debug.Helper which allows for easier
management of debug log levels. This also gets rid of the Debug field in
Config as it was really confusing on what logging that enabled, and also
firecracker-runtime.json. The log_level/LogLevel field in Config and the
firecracker-runtime.json has been renamed to log_levels and LogLevels.
=> Adds debug helper

runtime/Makefile, runtime/benchmark_test.go
NA
Previously the benchmark was measuring both CreateVM and StopVM due to
Go's benchmark's limitation.
Since we mostly care CreateVM, this change removes StopVM from
the measurement.
=> Measure only CreateVM

firecracker-control/service.go
The vm metadata is potentially sensitive and we don't want to log it.
=> Remove vm metadata from debug logs

runtime/service.go, runtime/service_integ_test.go
N/A
Populate the response fields in the Runtime Shim's CreateVM method and refactor redundant calls to determine the shim directory and VM namespace. 
=> Populate response for CreateVM in Runtime shim

.buildkite/setup_al2.sh, docs/getting-started.md, docs/quickstart.md
The log_level field doesn't work anymore.
=> Rename log_level to log_levels

runtime/integ_test.go, runtime/noop_jailer.go, runtime/runc_jailer.go, runtime/service_integ_test.go
NA
Firecracker's instance ID is appeared in Firecracker's log
file. Setting the ID makes the log easily trackable from clients.
=> Make Firecracker's instance ID configurable

go.mod, go.sum
https://github.com/containerd/containerd/pull/4495
Upgrade containerd to include the fix above.
=> Upgrade containerd to include devmapper's rollback fix

runtime/jailer.go, runtime/jailer_integ_test.go, runtime/runc_jailer.go, runtime/runc_jailer_test.go
The previous change (666cb5e) covers root filesystem files but it
doesn't work when a micro VM has additional drive mounts.
Since bind-mounts are created by modifying runc's configuration file,
calling bindMountFileToJail after starting runc is no-op.
To fix the issue, the jailer needs to scan through its additional drive
files and prepare them before they are replaced with stub drive files.
=> Fix bind-mount for additional drive files

.buildkite/al2_cleanup.sh, .dockerignore, runtime/Makefile, runtime/service_integ_test.go, tools/thinpool.sh
NA
Make FICD_DM_POOL and NUMBER_OF_VMS optional.
- For FICD_DM_POOL, thinpool.sh makes a loopback-based thinpool automatically.
- For NUMBER_OF_VMS, service_integ_test.go correctly handles `""`.
=> Make FICD_DM_POOL and NUMBER_OF_VMS optional

agent/service.go, internal/vm/task.go, runtime/service_integ_test.go
Clients would use errdefs package to programatically process the error.
=> Use codes.AlreadyExists correctly on Exec()

runtime/runc_jailer.go, runtime/service_integ_test.go
Previously firecracker-containerd keeps
/etc/containerd/firecracker-runc-config.json's Process.Args as is
if the value exists.
However passing VM ID (39e0475) doesn't work when it uses the exising
fixed value.
This change removes this confusing behavior and always overrides
Process.Args.
=> Override Process.Args regardless of the existing value

internal/vm/vsock.go, runtime/service.go
Prior to this commit, io would be proxied from the VM to the host, but
no timeout is provided to the proxy. So if vsock has an issue, the io
would forever try to connect to the vsock leading to an extraneous
amount of errors. This commit adds a simple default timeout, 5 second,
which will eliminate the extraneous amount of logs
=> Adding default vsock connection timeout

runtime/service.go, runtime/service_integ_test.go
cio.NewAttach didn't work with with firecracker-containerd. The operation is doing the following;
- Calls State() to find FIFO files that are connected to the container
- Passes the FIFO files to the client
- The client can open the FIFO files to interact with the containerd's stdio streams.
However firecracker-containerd was proxying the request to in-VM agent as is. As a result the FIFO files on the response are pointing the files inside the VM, which the client couldn't access.
=> Fix cio.NewAttach

internal/psutil.go, internal/vm/vsock.go
Signed-off-by: Jeremy Williams <ctrlaltdel121@gmail.com>
This change updates the usage of time.NewTicker to stop the tickers that it creates when the relevant function ends. In Go, when the ticker goes out of scope it does not stop being managed by the runtime (see https://github.com/golang/go/issues/8001).
When testing firecracker-containerd with frequent starts and stops of VMs, I noticed that over time the `containerd` process consumed more and more CPU. Via profiling I determined that this was because WaitForPidToExit() had been called over 100k times and had leaked over 100k 10ms tickers.
=> stop tickers in defer to prevent leak

Makefile
While firecracker-containerd doesn't use any new features, we'd like
to make sure firecracker-containerd is compatible with Firecracker
v0.24.0.
=> Update Firecracker from v0.23.0 to v0.24.1

.github/workflows/build.yaml
git-validation doesn't check Signed-off-by: line (aka DCO) in
merge commits. However, apparently Git cannot recognize merge
commits when one of the parents is missing.
This change fetches 30 commites instead of 21 just in case to
make sure we fetch merge commits with the associated parents.
=> Fetch 30 commits just in case to correctly check 20 commits

tools/image-builder/files_debootstrap/etc/systemd/system/firecracker.target.wants/getty.target
*Issue #477  :*
*Description of changes: In the Debian root filesystem getty service is masked, but getty target is not masked and still pointing to systemd binaries. Masking it by pointing it to /dev/null. With this we no longer see the messages like this
DEBU[2021-02-19T10:07:03.428545928Z] [    1.471698] systemd[756]: serial-getty@ttyS0.service: Executable /sbin/agetty missing, skipping: No such file or directory  jailer=noop runtime=aws.firecracker vmID=f7ac9a76-637a-4fb0-ac9c-8d933fabc4ab vmm_stream=stdout
This also saves 0.1 second for the VM to start up, as systemd repeatedly tries to enable serial consoles.
*
=> Disable systemd's getty services for debain based rootfs.

docs/architecture.md
We have moved the snapshotters from this repository to containerd
itself.
#480, but it won't close the issue yet :)
Remove snapshotters from the document.
=> Remove snapshotters from architecture.md

agent/Makefile, firecracker-control/cmd/containerd/Makefile, runtime/Makefile
Most of the binaries use internal/ and other packages inside this
source tree. So, Makefile should have them to correctly rebuild
binaries when dependencies change.
=> Rebuild binaries when dependencies change

runtime/service_integ_test.go
The test must have _Isolated suffix to make it work on
"make integ-test".
NA
Renamed the test function to be picked-up by Makefile.
=> Enable tests regarding Pause/Resume

Makefile
Signed-off-by: Royce Zhao <qiqinzha@amazon.com>
Update download link to fetch vmlinux kernel and its sha256sum. The new vmlinux kernel will support memory ballooning feature. More information about the prerequisites for the kernel to support memory ballooning can be found [HERE](https://github.com/firecracker-microvm/firecracker/blob/main/docs/ballooning.md#prerequisites)
=> Update vmlinux kernel

.github/workflows/build.yaml, README.md, docs/getting-started.md, examples/taskworkflow.md, internal/vm/vsock.go, tools/docker/Dockerfile.firecracker-builder
firecracker-containerd no longer uses `master` branch since 435ade4.
=> Use main instead of master

README.md, docs/getting-started.md, docs/quickstart.md
This PR has two things changed. 
1. There is a merged PR #495 for updating kernel download link on Makefile. I think we should also update the kernel download link on docs to keep them consistent. The new kernel download link comes from https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md#running-firecracker
2. Update the slack channel invitation link, as https://github.com/firecracker-microvm/firecracker-go-sdk/issues/340 is pointing out. 
Signed-off-by: Royce Zhao <qiqinzha@amazon.com>
=> Update outdated slack invitation & kernel download links

examples/Makefile
TEST_POOL is used to pass a pool name for the example we use for testing
firecracker-containerd inside the docker container. However in the Makefile
TEST_POOL is passed empty to the thinpool.sh thich causes the script to
return without creating any pool. Similarly in the entrypoint.sh which
is run by the docker container we end up using an empty string for
pool_name to be added in the generated devmapper.toml file. This leads
to an issue where firecracker-containerd starts without devmapper
configiured and hence the taskworkflow program fails as it passed
devicemapper as the snapshotter to use for this example. The fix is to have
a default value for TEST_POOL in Makefile. Buildkite is not impacted because
there we explicitly pass the build number as the test pool name.
Signed-off-by: …
=> Fix for integ-test failure in docker based example.

.buildkite/pipeline.yml
The 15 minutes timeout was arbitrary chosen in the past. As we have
more tests, this step tends to exceed the timeout.
=> The runtime tests take more than 15 minutes to finish

runtime/service_integ_test.go
Signed-off-by: Alakesh Haloi <alakeshh@amazon.com>
StopVM works even when VM is in Paused state. Hence this addition call to resume in the test is no longer required.
=> Remove resume before stopVM in test, as it is no longer needed for stopVM

internal/fsutil.go, runtime/jailer_integ_test.go, runtime/runc_jailer.go, runtime/service_integ_test.go
We tried to attach an extra block device containing filesystems but received **file exists** error. This error is only existed when we used runc_jailer (will call it jailer in the following context) + `DriveExposePolicy_BIND`. Not surprisingly, without the jailer, the extra block device was successfully mounted without any issue.
**Root cause is that the same block device being mounted twice. The duplicated mountings cause an error returned.**
Detailed error message is below
```
An error is returned "rpc error: code = Unknown desc = failed to create VM: failed to patch drive mount stub: failed to expose
patched drive contents to jail: file exists". This commit is for fixing it.
```
The jailer config was
```
proto.JailerConfig{
UID:               300001,
GID:               300001, …
```
=> Fix extra block device bind mounting

config/config_test.go, docs/getting-started.md, docs/logging.md, examples/etc/containerd/firecracker-runtime.json, runtime/README.md
Remove obsolete `cpu_count` runtime config from documentations, since the option has already been removed from the runtime in https://github.com/firecracker-microvm/firecracker-containerd/pull/372.
Signed-off-by: Jingkai He <jingkai@hey.com>
*Issue #, if available:* https://github.com/firecracker-microvm/firecracker-containerd/issues/444 (somehow closed)
=> Remove obsolete `cpu_count` runtime config from documentations

.github/workflows/build.yaml, go.sum
Apparently it doesn't work with Go 1.16 currently.
=> Build firecracker-containerd on more modern dependencies

Makefile
Kernel binary got updated and hence needs the sha needs update too. Without that we have failures like this
curl --silent --show-error --retry 3 --max-time 30 --output default-vmlinux.bin \
"https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/kernels/vmlinux.bin"
echo ""bc7e2dbf12cf7038937abf42056f6bcd405d3eef4d27aaa3016f0ba15069ae4b" default-vmlinux.bin" | sha256sum -c -
default-vmlinux.bin: FAILED
=> Update sha256 for x86_64 vmlinux binary

.buildkite/setup_al2.sh, examples/etc/containerd/firecracker-runtime.json, runtime/integ_test.go, tools/image-builder/Makefile
Linux kernel's sublevel exceeded 255 in 4.9.x and 4.14.x releases.
However Debian's libc6 package assumed that the sublevel < 255 and had
an explicit check in the package.
While the check has been removed, we have to upgrade our Debian to
at least Debian 11 "bookwarm" to have the change.
https://lwn.net/Articles/845120/
https://lore.kernel.org/stable/YVAhOlTsb0NK0BVi@kroah.com/T/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987266
=> Use Debian 12 "bookworm" to workaround Linux's sublevel issue

Makefile, tools/image-builder/Makefile
The target was calling deboostrap but its file tree was in /src/tmp,
which was removed with the container.
This change moves /src/tmp from an anonymous volume to a named
volume to keep the result.
https://docs.docker.com/storage/volumes/
=> Make "make test-images" faster

Makefile, tools/image-builder/Makefile
Caching /src/tmp doesn't work since debootstrap assumes an empty directory.
In addition to that, sharing the volume across multiple BuildKite jobs
wouldn't work correctly.
This reverts commit 0df8c044428a756fddc2abaf57e8b0b7eaa54c52.
=> Revert "Make "make test-images" faster"

Makefile, tools/docker/Dockerfile.integ-test, tools/docker/Dockerfile.proto-builder, tools/docker/Dockerfile.runc-builder
=> Upgrade Go from 1.13 to 1.15

tools/docker/Dockerfile.integ-test
critest is extracted to /tmp in the image but never removed after it is
installed. Remove it to keep image size minimal.
=> Remove duplicate critest from test image

agent/service.go, go.mod, internal/vm/mount.go, internal/vm/mount_test.go, internal/vm/oci.go, runtime/firecrackeroci/vm.go, runtime/service.go, runtime/vm/mount.go
With this change, if a mount is returned from a snapshotter
where the type is prefixed with "vm:", then firecracker-containerd
will not assume it is a block device and will pass the mount
information directly to the agent in the VM to handle mounting
the container's rootfs.
=> Add ability to launch containers with vm local rootfs.

internal/vm/dir_test.go, internal/vm/ioproxy_test.go, runtime/drive_handler_test.go, runtime/jailer_test.go, runtime/runc_jailer_test.go, runtime/service_integ_test.go, runtime/service_test.go
A small testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

.golangci.yml, Makefile, agent/service.go, internal/common_test.go, internal/vm/oci.go, runtime/firecrackeroci/vm.go, runtime/jailer_integ_test.go, runtime/service.go
#567 
Bump golangci-lint from v1.21.0 to v1.44.2
Removes deprecated linters and adds recommended replacement linters
'revive' and 'exportloopref'.
Marks G306 and G307 as excluded until those errors can be audited
seperately.
Removes an instance of unused variable flagged by 'unused' linter.
Updates few instances of local variable names to be inline with 'revive'
naming standards.
Updates few instances of exported function names to be inline with
'revive' naming standards.
Fixes a few instances where 'append' result was not stored in original
slice.
=> chore: upgrade golangci-lint to v1.44.2

Makefile, go.mod, snapshotter/.gitignore, snapshotter/Makefile, snapshotter/app/service.go, snapshotter/config/config.go, snapshotter/config/config.toml.example, snapshotter/config/config_test.go, snapshotter/demux/cache/cache.go, snapshotter/demux/cache/snapshotter_cache.go, snapshotter/demux/cache/snapshotter_cache_test.go, snapshotter/demux/internal/failing_snapshotter.go, snapshotter/demux/internal/successful_snapshotter.go, snapshotter/demux/proxy/address/http_resolver.go, snapshotter/demux/proxy/address/http_resolver_test.go, snapshotter/demux/proxy/address/resolver.go, snapshotter/demux/proxy/snapshotter.go, snapshotter/demux/snapshotter.go, snapshotter/demux/snapshotter_test.go, snapshotter/internal/http_address_resolver.go, snapshotter/internal/mount/collection.go, snapshotter/internal/mount/collection_test.go, snapshotter/main.go
This change adds a demultiplexing snapshotter application which allows
for proxying remote snapshotter requests across the microVM threshold.
The snapshotter includes a vsock lookup mechanism via namespace
specified via configuration file. Also includes a cache mechanism
for vsock lookup results.
=> feat: add demultiplexing snapshotter

Makefile
**tl;dr**
I'm using Arch linux and ironically can't build this because
I don't have the "arch" command. I dug a bit and found it's a
wrapper to 'uname -m' so I just replaced it.
**Longer version**
`arch` is a wrapper for `uname -m` in GNU coreutils [0]
However, unlikely the `uname` command, the `arch` command
is not as available.
It also looks like the arch command is being carried on in
UNIX history as a mechanism for retrocompatibility, here's a
manpace for solaris [1] saying:
> This command is provided for compatibility with previous releases and its use is discouraged. Instead, the uname command is recommended. See uname(1) for usage information.
[0] https://github.com/coreutils/coreutils/blob/00ea4bacf6063ccc125209d5186f8f2382c6f0d4/src/coreutils-arch.c
[1] …
=> Makefile: replace the 'arch' command with 'uname -m'

docs/getting-started.md, docs/logging.md, docs/quickstart.md
Our getting started guides recommend a pre-built kernel at version 4.14.
Cgroups v2 require kernel 4.15 and our image builder scripts now use
Debian 11 which enabled cgroups v2 by default.
=> Disable cgroups v2 in our getting started guides

snapshotter/.gitignore, snapshotter/Makefile, snapshotter/internal/http_address_resolver.go
Requires #594 
Change the internal mechanics to query firecracker-containerd
instead of using the requests namespace as the VM ID.
This internal mechanism will be used for integration testing.
=> refactor: internal HTTP address resolver

snapshotter/demux/cache/cache.go, snapshotter/demux/cache/snapshotter_cache.go, snapshotter/demux/cache/snapshotter_cache_test.go
Add a List interface to Cache and implement it for SnapshotterCache. The
List interface returns keys existing in a cache.
These changes also modify the SnapshotterCache to use a RWMutex rather
than a vanilla Mutex https://pkg.go.dev/sync#RWMutex . This way any
number of readers can read from cache, but only one writer may acquire
the lock at a time.
=> Add List interface to snapshotter cache

snapshotter/app/service.go, snapshotter/config/config.go, snapshotter/config/config.toml.example, snapshotter/config/config_test.go, snapshotter/demux/proxy/address/http_resolver_test.go, snapshotter/demux/proxy/address/resolver.go
#602 task 1
These changes update the Response of the HTTP resolver to include the
port for pulling metrics from a remote snapshotter. They also include initial update to configuration.
=> Update HTTP resolver to return metrics port

Makefile
Previously, make demo-network only worked the first time
because the target did not depend on the soruce file. With
this change, make demo-network will reinstall the CNI configs
every time the source file changes
=> Make fcnet targets depend on source file

snapshotter/app/service.go, snapshotter/config/config.go, snapshotter/config/config.toml.example, snapshotter/config/config_test.go, snapshotter/demux/cache/cache.go, snapshotter/demux/cache/snapshotter_cache.go, snapshotter/demux/cache/snapshotter_cache_test.go, snapshotter/demux/metrics/discovery/service_discovery.go, snapshotter/demux/metrics/proxy.go, snapshotter/demux/proxy/address/http_resolver_test.go, snapshotter/demux/proxy/address/resolver.go, snapshotter/demux/proxy/snapshotter.go, snapshotter/demux/snapshotter_test.go
Addresses tasks 2 and 3 (metrics proxy / service discovery) of #602 
Snapshotters handled by the the demux snapshotter may expose metrics
endpoints. These changes modify the newProxySnapshotterFunc to
optionally start a metrics proxy server when a new proxy snapshotter is
initialized. The demux snapshotter's cache has been modified to contain
a map of `RemoteSnapshotter`s, which are simply wrappers around the
containerd snapshotter construct and a new type for metrics proxies.
These changes also introduce a mechanism for discovering these proxied
snapshotter metrics for the purposes of aggregating these metrics.
By submitting this pull request, I confirm that my contribution is made under …
=> feat: add snapshotter metrics proxy and service discovery mechanism

.buildkite/pipeline.yml
Previously 746fc78 (#593) changed examples/ and Amazon Linux 2's tests.
However runtime/ is still having 10 minutes timeout from Go's default,
30 minutes timeout from BuildKite.
This commit removes them and adding much longer timeout.
=> Allow each test under runtime/ to run for an hour at maximum

examples/Makefile
runtime/Makefile and examples/Makefile are using different pools, while
tools/thinpool.sh is assuming that we only have a single loopback-based
thinpool.
=> Use "testpool" as a loopback-based thinpool 

snapshotter/app/service.go, snapshotter/internal/http_address_resolver.go
http-address-resolver:
* Call GetVMInfo with namespace set
* Return SnapshotterPort
demux-snapshotter:
* Dial the returned address verbatim without
trying to parse it into a URL
=> Fix minor demux snapshotter issues

runtime/service_integ_test.go
TestMultipleVMs_Isolated is still unstable (see #581). Apparently having
multiple simultaneous requests from the same client is known to be
problematic (see https://github.com/containerd/ttrpc/issues/72).
This commit workarounds the issue by making a client per VM.
#581
See above
=> Make TestMultipleVMs_Isolated stable by not sharing its ttrpc client

Makefile
This reverts commit 9b5912e368802ba1cf19fd3aaa250c9fee9b5a40.
Signed-off-by: Swagat Bora <swagatbora90@gmail.com>
This reverts the changes as mentioned in #619. A fix for the same issue has been merged with https://github.com/vbatts/git-validation/pull/55.
`make lint` is now passing
```
[ec2-user@ip-172-31-9-211 firecracker-containerd]$ make lint
/home/ec2-user/firecracker-containerd/bin/git-validation -run DCO,short-subject -range HEAD~20..HEAD
* e646a57 "Revert \"Fix lint\"" ... PASS
* d99a632 "Merge pull request #620 from Kern--/lint" ... PASS
* 9b5912e "Fix lint" ... PASS
* 78381c3 "Allow configuration of block_device cache strategy in firecracker (#615)" ... PASS
* b88e16e "Merge pull request #604 from ginglis13/upgrade-imgcrypt" ... …
```
=> Revert "Fix lint"

.github/workflows/build.yaml, runtime/volume_integ_test.go, volume/set.go, volume/volume.go, volume/volume_test.go
Since firecracker-containerd puts containers in VMs, mounting the host's
directories is not straightforward.
This commit adds "volume" package that makes an empty ext4 image to pack
and create helper functions around to make the image usable from
containers.
=> Support volumes

snapshotter/app/service.go, snapshotter/demux/metrics/proxy.go, snapshotter/demux/metrics/proxy_test.go, snapshotter/demux/proxy/snapshotter.go
This change introduces a Monitor type which is made aware of a metrics
proxy's closure via a channel. It contains the logic for port selection
for a new metrics proxy and port freeing for a metrics proxy that has
been shut down.
For maintainability, open to discussions around moving Monitor implementation to its own file in the metrics package.
refactoring done to move metrics proxy server initialization to its own function, as well as removal of `enable` configuration option for metrics. Included some unit tests for the `metrics` HTTPResponseHandler
resolves #607
=> add monitoring of metrics proxy servers

tools/image-builder/files_stargz/etc/containerd-stargz-grpc/config.toml, tools/image-builder/files_stargz/etc/systemd/system/firecracker.target.wants/metrics-socat.service, tools/image-builder/files_stargz/etc/systemd/system/metrics-socat.service
configure socat to forward requests to in-Vm metrics server being hosted by remote snapshotter, and configure remote snapshotter to emit metrics. 
Tested locally with `firectl` and `socat`, my relative paths to kernel and remote snapshotter rootfs used here:
```
$ make image-stargz
$ sudo ./firectl -d -t  \
--kernel=./hello-vmlinux.bin \ 
--root-drive=./tools/image-builder/rootfs-stargz.img  \
--kernel-opts="console=ttyS0 noapic reboot=k panic=1 pci=off nomodules ro systemd.journald.forward_to_console systemd.unit=firecracker.target init=/sbin/overlay-init"   \
--vsock-device=./test.sock:1
```
in another shell:
```
$ sudo socat - UNIX-CONNECT:test.sock
CONNECT 10001
OK 1073741824
GET /metrics HTTP/1.1
Host:localhost
....(metrics)....
``` …
=> add metrics config to remote snapshotter rootfs

internal/integtest/config.go, internal/integtest/prepare.go, internal/integtest/shim.go, runtime/benchmark_test.go, runtime/cni_integ_test.go, runtime/integ_test.go, runtime/jailer_integ_test.go, runtime/jailer_test.go, runtime/limits_integ_test.go, runtime/service_integ_test.go, runtime/volume_integ_test.go
Prep for #595 
Refactor some of the common integration test setup code into a reusable module for integration tests.
=> refactor: integration test common code into internal module

.buildkite/pipeline.yml
The concurrency group could cause a deadlock and we no longer make a
bunch of loopback devices during the tests.
=> Don't wait "losetup -D"

runtime/volume_integ_test.go, tools/docker/Dockerfile.integ-test, volume/set.go
It isn't fully transparent though.
=> Make volume package usable from non-Firecracker runtimes

internal/network_test_utils.go, runtime/cni_integ_test.go
While running integration tests, I ran into issues with tests not cleaning up the devices on failure.
=> fix: cleanup of network devices for CNI tests

.buildkite/pipeline.yml, Makefile, runtime/runc_jailer_test.go
internal.RequiresIsolation is used to run a test in containers.
It is convinient but slower than normal tests.
This commit reduces the usage of internal.RequiresIsolation(t).
Many of them only need root privileges.
=> Reduce "isolated" tests to speed up runtime tests

Makefile, runtime/service_integ_test.go, tools/image-builder/Makefile, tools/image-builder/agent.sh
There are multiple rootfs files to simulate multiple failure cases.
However building a rootfs image is a slow operation in our build
process and affects our productivity.
This commit consolidates the "broken" rootfs files into one and
use Linux's boot parameter to simulate multiple failure cases.
=> Reduce the number of "broken" rootfs files

internal/integtest/containerd.go, internal/integtest/firecracker.go, internal/integtest/network.go, internal/integtest/runtime.go, runtime/benchmark_test.go, runtime/cni_integ_test.go, runtime/integ_test.go, runtime/jailer_integ_test.go, runtime/limits_integ_test.go, runtime/service_integ_test.go, runtime/volume_integ_test.go
Refactor common integ test functions to internal integtest package.
=> refactor: integ test common code into internal package

.buildkite/pipeline.yml, runtime/service_integ_test.go
This test separates TestMultipleVMs_Isolated's 100 VMs run from other
tests by
- Changing the number of VMs from 100 to 10 in the runtime tests
- Keeping 100 VMs run as a separate job with its own concurrency group.
In addition to that, the test increases the number of VMs slowly,
instead of running 100 VMs from the beginning to figure out the breaking
point.
=> Separate TestMultipleVMs_Isolated from other tests

.buildkite/al2_pipeline.yml, .buildkite/pipeline.yml, runtime/service_integ_test.go
This commit makes the test less painful to run
- By reducing the number of VMs from 100 to 50
- By reducing the timeout to fail sooner
=> Make TestMultipleVMs_Isolated less painful to run

snapshotter/demux/cache/cache.go, snapshotter/demux/cache/snapshotter_cache.go, snapshotter/demux/cache/snapshotter_cache_test.go, snapshotter/demux/snapshotter.go, snapshotter/demux/snapshotter_test.go
#652 
This PR adds the ability for no namespaced walks on the demux snapshotter to be broadcasted to all cached snapshotters.
=> add: no namespace walk support to demux snapshotter

snapshotter/demux/internal/failing_snapshotter.go, snapshotter/demux/internal/successful_snapshotter.go, snapshotter/demux/proxy/snapshotter.go, snapshotter/demux/snapshotter.go, snapshotter/demux/snapshotter_test.go
This PR adds the ability for asynchronous cleanup requests to be proxied to remote snapshotters by the demux snapshotter.
=> add: asynchronous cleanup support to demux snapshotter

snapshotter/app/service.go, snapshotter/demux/metrics/proxy.go, snapshotter/internal/http_address_resolver.go, tools/image-builder/files_stargz/etc/systemd/system/metrics-socat.service
fix a scoping issues in demux snapshotter issuer. initialize monitor
properly in metrics proxy server. add metrics info to example HTTP
address resolver
=> minor demux snapshotter metrics bug fixes

Makefile
Asking "Continue? (y/n)" doesn't work under CI environments.
=> Firecracker's devtool shouldn't wait the user's response

snapshotter/demux/cache/snapshotter_cache.go
I have been giving bad advice and suggesting that we don't use read locks in the snapshotter cache. Turns out this is unsafe and can cause runtime panics if we concurrently read and write the map.
https://go.dev/doc/faq#atomic_maps
=> Fix unsafe map access in snapshotter cache

.buildkite/pipeline.yml, .gitignore, Makefile, internal/integtest/runtime.go, snapshotter/.gitignore, snapshotter/Makefile, snapshotter/internal/integtest/stargz/fs/config/config.go, snapshotter/internal/integtest/stargz/fs/source/source.go, snapshotter/service_integ_test.go, tools/docker/Dockerfile.integ-test, tools/docker/config.toml, tools/docker/entrypoint.sh, tools/image-builder/files_stargz/etc/systemd/system/stargz-snapshotter.service
#595 
Adds integration test to launch a task in using a remote snapshotter running inside the microVM.
=> add: integration test for remote snapshotter

.buildkite/pipeline.yml, snapshotter/service_integ_test.go
As noted in #671, do not pass `*testing.T` to goroutines.
=> fix: do not pass testing.T to goroutines in remote snapshotter tests

.buildkite/pipeline.yml, snapshotter/app/service.go, snapshotter/config/config.go, snapshotter/config/config_test.go, tools/docker/entrypoint.sh
#673 
Tune vsock dial based on Buildkite host performance. Should be made more robust by #689 
=> fix: tune vsock dial for buildkite hosts

runtime/runc_jailer.go, runtime/runc_jailer_test.go
Since m.HostPath could take arbitrary strings, the result of
filepath.Join() could point files outside of the jail (j.RootPath).
=> prepareBindMounts must not modify files outside of the jail

snapshotter/metrics_integ_test.go, tools/docker/entrypoint.sh
This PR adds happy path integration testing for metrics. TODO included
for testing changes in service discovery response as VMs are started and
stopped and evicted from the demux snapshotter cache.
=> add metrics integration tests

.github/workflows/build.yaml, Makefile
N/A
1. Update golangci-lint to pull 1.46.2
2. Fix makefile lint dependency installation
=> chore: pull v1.46.2 of golangci-lint

runtime/service.go
Signed-off-by: Henry Wang <henwang@amazon.com>
Do not wait for vm ready during shim clean up.
Sample log lines:
```
ul 22 19:53:50 ip-10-194-10-130 firecracker-containerd: time="2022-07-22T19:53:50.067507228Z" level=error msg="failed to delete" cmd="/usr/sbin/containerd-shim-aws-firecracker -namespace TestSchema1Image
Manifest1658519613 -address /run/firecracker-containerd/containerd.sock -publish-binary /usr/sbin/firecracker-containerd -id TestSchema1ImageManifest-3684275467 -bundle /run/firecracker-containerd/io.cont
ainerd.runtime.v2.task/TestSchema1ImageManifest1658519613/TestSchema1ImageManifest-3684275467 delete" error="exit status 1"
Jul 22 19:53:50 ip-10-194-10-130 firecracker-containerd: time="2022-07-22T19:53:50.067562517Z" level=warning msg="failed to …
```
=> Do not wait for vm ready during shim clean up

tools/image-builder/Makefile
Signed-off-by: Vaishnavi Vejella <vvejella@amazon.com>
*Issue:*
Kernel is panicking and not syncing with AMD instance while working with firecracker-containerd.
During performing sanity checks on Firecracker-containerd, the AMD ec2 instance got failed. It is due to panicking of kernel and systemd causes segmentation fault while pulling an image. Then we downgraded the Debian version of rootfs from bokworm to bullseye to work.
=> Downgrading rootfs from bookworm to bullseye

docs/getting-started.md, docs/quickstart.md
n/a
Noticed in going through the firecracker-containerd quickstart for Amazon Linux that by
default, gcc is not installed. add that as a yum package to be
installed. Just copy-pasting as is will run into an error of gcc not found.
=> add gcc to quickstart yum packages and getting started prerequisites

config/config_test.go, runtime/service_test.go
Only the Intel instance is supported with CPUTemplate. By setting the CPUTemplate value to an empty string, we are testing our instance in this case.
Signed-off-by: Vaishnavi Vejella <vvejella@amazon.com>
Issue: When testing an AMD instance against Firecracker-containerd, but the BuildKite pipeline tests fail due to CPUTemplate, which is not supported by non-intel instance.
Description of changes: By assigning an empty string to the CPUTemplate field we are conducting tests against the instance to check, if this field is supported by `internal.SupportCPUTemplate()`
=> Remove CPUTemplate to test non-intel instance

Makefile, internal/vm/oci.go, runtime/cpuset/cpuset_builder.go, snapshotter/demux/metrics/discovery/service_discovery.go, snapshotter/demux/metrics/proxy.go, snapshotter/internal/http_address_resolver.go
Go 1.19 support was added in golangci-lint v1.48.0. Resolves new warnings from gofmt and gosec.
=> Upgrade golangci-lint to v1.48.0

runtime/integ_test.go, runtime/jailer_integ_test.go, runtime/service_integ_test.go
Some of our tests are assuming cgroups v1, but our BuildKite hosts are
now using cgroups v2.
=> Support cgroup v2

Makefile, tools/docker/Dockerfile.integ-test, tools/docker/Dockerfile.proto-builder, tools/docker/Dockerfile.runc-builder
dependencies from containernetworking reference unsafe.Slice, a construct that was first introduced in go1.17
=> upgrade builder and integ test images to go1.17

Makefile
Closes #723 
As the project's BuildKite infrastructure is expanding to test against the ARM architecture, the image used for remote snapshotter testing will need to be built for ARM. By pulling the image and optimizing with the --all-platforms flag, we can provide ARM support.
The image can be found at https://github.com/orgs/firecracker-microvm/packages/container/package/firecracker-containerd%2Famazonlinux. 
*Testing*
I followed the guide in https://github.com/firecracker-microvm/firecracker-containerd/tree/main/snapshotter/demux to build and push the image. 
I pulled the esgz image, ref `ghcr.io/firecracker-microvm/firecracker-containerd/amazonlinux:latest-esgz`, and ensured the arm …
=> build and push esgz image for all platforms

.buildkite/al2_pipeline.yml, .buildkite/pipeline.yml, Makefile, tools/docker/Dockerfile.integ-test, tools/image-builder/Dockerfile.debian-image
We don't have to mix Debian 9 (stretch), 10 (buster) and 11 (bullseye).
=> Use Debian 11 (bullseye) everywhere

tools/docker/Dockerfile.integ-test
Signed-off-by: Vaishnavi Vejella <vvejella@amazon.com>
*Issue:*
**Containerd** for ARM is not present to get runc shim and **Critest** binary is also not there for ARM architecture.
We can install appropriate binaries by providing the Architecture to both Containerd and Critest in the Dockerfile.
=> Set ARCH to CTRD and CRITEST

examples/cmd/remote-snapshotter/go.sum, go.mod, go.sum
Upgrade runc from 1.1.3 to 1.1.5 based on failing dependbot [PR](https://github.com/firecracker-microvm/firecracker-containerd/pull/735).
=> Update runc to 1.1.5 from 1.1.3

examples/cmd/remote-snapshotter/go.sum, go.mod, go.sum
Upgrade `github.com/containerd/fifo` to v1.1.0. 
This is the second release of containerd/fifo that includes various bug fixes since v1.0.0 was tagged.
https://github.com/containerd/fifo/releases/tag/v1.1.0
=> update github.com/containerd/fifo to v1.1.0

docs/quickstart.md, tools/docker/Dockerfile.proto-builder, tools/docker/Dockerfile.runc-builder, tools/image-builder/README.md
In #726 we upgraded to Debian 11 most of the places. 
We have some leftovers in the repo using Debian 9(stretch) which was out of support and the [stretch package repo seems removed](https://packages.debian.org/stretch/) recently causing [apt-get installation issue](https://github.com/firecracker-microvm/firecracker-containerd/actions/runs/4799041254/jobs/8538393247?pr=742#step:9:115) in CI. 
This PR upgrades reminder of Debian 9(stretch) and Debian 10(buster) to Debian 11.  
=> Upgrade to Debian 11(Bullseye) everywhere

docker-credential-mmds/go.mod, docs/getting-started.md, docs/quickstart.md, examples/cmd/remote-snapshotter/go.mod, go.mod
Signed-off-by: Jean Delannoy ([jdelannoy@gmail.com](mailto:jdelannoy@gmail.com))
Issue https://github.com/firecracker-microvm/firecracker-containerd/issues/731
Description of changes:
Update the min required Go version from the getting-started and quickstart guides
=> upgrade the min version of Go from the docs 

examples/cmd/remote-snapshotter/go.mod, examples/cmd/remote-snapshotter/go.sum, go.mod, go.sum
N/A
Updates containerd/containerd dependency to v1.6.20
Updates containerd/ttrpc dependency to v1.1.1
=> Update containerd to v1.6.20 and ttrpc to v1.1.1 for bug fixes

.github/workflows/build.yaml
Adds protections to disable caching for corner case when compiling across multiple Linux distribution versions would result in collisions.
N/A
Upgrades actions/setup-go to v4 which has Go caching enabled by default. Explicitly disabling Go caching right now due to an upstream bug which will result in collisions when compiling across multiple versions of the same Linux distribution.
=> Upgrade actions/setup-go to v4 in CI workflow

examples/cmd/remote-snapshotter/go.mod, examples/cmd/remote-snapshotter/go.sum, go.mod, go.sum
Includes fix for closing ttrpc server connection on client disconnect during message read.
#749 
Updates containerd/ttrpc dependency to v1.1.2
=> Update containerd/ttrpc to v1.1.2

agent/drive_handler.go
N/A
Log diving on a issue and found the underlying umount syscall error was not being returned for unmounting drive failures.
=> Include underlying error for unmount drive error

runtime/service.go
N/A
Stdin/stdout/stderr fields can container full shim logger binary URIs which may container sensitive information such as logging credentials. Since there is no simple method for redacting this information at runtime, the best solution is to not log them to disk.
=> Remove create task stdin/stdout/stderr fields.

runtime/service_test.go
Validates #781 
This change adds a unit test to validate when launching a container with the firecracker runtime the shim implementation will not log the stdout/stderr shim logger binary URI to disk.
=> Add unit test to not log stdout or stderr fields on create task request

examples/cmd/remote-snapshotter/go.mod, examples/cmd/remote-snapshotter/go.sum, go.mod, go.sum
Closes #783 and #784
This change updates the transitive dependency on golang.org/x/net to v0.24.0
=> Update golang.org/x/net dependency to v0.24.0

tools/docker/Dockerfile.proto-builder
Proto checks can failure intermittently due to outdated protoc-gen-go tooling in proto-builder container.
See https://github.com/firecracker-microvm/firecracker-containerd/actions/runs/8942291119
This change updates the protoc-gen-go tooling to v1.33 to align with the version used to generate the protogen code.
=> Update protoc-gen-go to v1.33 in proto-builder container

agent/error.go, agent/error_test.go
There is a race between firecracker-containerd replacing the stub drive with the actual drive and mounting this drive. When the disk is replaced the kernel will schedule asynchronous work in virtblk_config_changed. In the meantime firecracker-containerd can proceed and already send a mount command to the agent running in the guest. This mount operation will, however, fail because the guest kernel still sees the stub drive with only 512 bytes in size. The resulting error code is a ENOMEM in this case. This commit therefore adds this as an retryable error code to accommodate for this situation.
The issue can be reproduced when an artificial msleep(1000) is added in virtblk_config_changed_work. This produced the following error:
error="failed to get stub drive for task \"test\": failed to …
=> agent: retry mount on ENOMEM

tools/docker/Dockerfile.integ-test, tools/docker/Dockerfile.proto-builder, tools/docker/Dockerfile.runc-builder, tools/docker/Dockerfile.stargz-builder, tools/image-builder/Dockerfile.debian-image
=> use ECR public images

.buildkite/pipeline.yml
Buildkite `runtime isolated tests` are known to be flaky and mostly due to stdout streaming issues. Until we have a formal root cause and fix, adding a retry mechanism to the step to remove any flakiness. 
=> Retry buildkite isolated tests since they are known to be flaky

.github/workflows/build.yaml
Ubuntu 20.04 is no longer supported from GitHub actions, so this change removes them to avoid failing our CI.
=> Remove Ubuntu 20.04 runners

Makefile, docker-credential-mmds/Makefile
*Issue #819, if available:*
Add a `STATIC_DOCKER_CREDENTIAL_MMDS` flag to the `docker-credential-mmds` build process (similar to the agent's build process) to enable static linking ( set `CGO_ENABLED=0`) and avoid dependency on the host's glibc version.
=> #819: fix: enable static linking for docker-credential-mmds to resolve glib
